### ISSUE TITLE
Timeout Error. Version 1.1.0

### ISSUE THREAD

**Issue by Dreistein19** [PLCHome/ioBroker.growatt#10]
Admin 5.x Oberfläche :

growatt.0 | 2021-05-26 19:07:27.547 | error | Logout:Error: timeout of 1000ms exceeded
growatt.0 | 2021-05-26 19:09:30.671 | error | Logout:Error: timeout of 1000ms exceeded

Admin 4.x Oberfläche:

growatt.0 | 2021-05-26 20:53:49.956 | error | (20087) Login:{"message":"timeout of 1000ms  exceeded","name":"Error","stack":"Error: timeout of 1000ms exceeded\n     at createError  (/opt/iobroker/node_modules/axios/lib/core/createError.js:16:15)\n

Der Fehler tritt nicht immer auf. Ein Problem auf meiner Seite ?
Der Fehler war bei 1.0.1 nicht vorhanden,

**Comment by PLCHome** [comment]
Hi, mit der 1.1.0 ist ein Time-out von einer Sekunde hinzugekommen. Abgesehen von der Meldung im Log laufen nach den Fehlermeldungen irgendwann wieder Daten ein oder musst der Adapter neu gestartet werden?

**Comment by Dreistein19** [comment]
Adapter neu gestartet, Fehler bleibt.
Daten kommen normal.

**Comment by PLCHome** [comment]
Kommt der Fehler sporadisch ein oder zweimal oder im 2,5s Takt andauernd?

**Comment by Dreistein19** [comment]
Fehler (ist ja eigentlich keiner) tritt immer noch auf. Aber sehr , sehr selten.
Beispiel Heute :

growatt.0 | 2021-05-29 18:01:41.500 | error | (1189) Login:{"message":"timeout of 5000ms  exceeded","name":"Error","stack":"Error: timeout of 5000ms exceeded\n     at createError  (/opt/iobroker/node_modules/axios/lib/core/createError.js:16:15)\n

growatt.0 | 2021-05-29 14:08:52.804 | error | (1189) Login:{"message":"timeout of 5000ms  exceeded","name":"Error","stack":"Error: timeout of 5000ms exceeded\n     at createError  (/opt/iobroker/node_modules/axios/lib/core/createError.js:16:15)\n

growatt.0 | 2021-05-29 14:03:14.830 | error | (1189) Login:{"message":"getaddrinfo EAI_AGAIN  server.growatt.com","name":"Error","stack":"Error: getaddrinfo EAI_AGAIN  server.growatt.com\n    at GetAddrInfoReqWrap.onlookup [as oncomplete]  (dns.js:

Wie gesagt, wenn das nur sporadisch auftritt, Kein Problem.

**Comment by kopierschnitte** [comment]
Also bei mir kommt der gleiche Fehler wie bei @Dreistein19 mittlerweile bis zu 20x pro Tag. Wäre es vielleicht eine Idee, das Timeout noch höher zu setzen (oder gar individuell einstellbar zu machen)?
Scheinbar hat deren Server ein paar Lastprobleme in den letzten Monaten...
