### ISSUE TITLE
new js-controller, please update

### ISSUE THREAD

**Issue by MeisterMio** [PLCHome/ioBroker.growatt#12]
Please update for better compatibility with js-controller 3.3.X

growatt.0 | 2021-08-09 10:43:43.308 | info | State  value to set for  "growatt.0.159047.devices.QNB284305C.deviceData.timeServer" has to be  type "number" but received type "object"
-- | -- | -- | --
growatt.0 | 2021-08-09 10:43:43.306 | info | State  value to set for  "growatt.0.159047.devices.QNB284305C.deviceData.lastUpdateTime" has to  be type "number" but received type "object"
growatt.0 | 2021-08-09 10:43:43.256 | info | State  value to set for "growatt.0.159047.devices.QNB284305C.historyLast.time"  has to be type "number" but received type "object"
growatt.0 | 2021-08-09 10:43:43.253 | info | State value to set for "growatt.0.159047.plantData.creatDate" has to be type "number" but received type "object"

**Comment by PLCHome** [comment]
is fixed in unstable

**Comment by PLCHome** [comment]
That has been fix since version 1.0.0. The affected objects must be deleted; when the adapter is restarted, they are created correctly.
