### ISSUE TITLE
Write Data

### ISSUE THREAD

**Issue by iobroker99** [PLCHome/ioBroker.growatt#15]
Is it possible to expand the Adapter so that we could write/set data? 
My problem: the Growatt SPH always stays in "normal mode" and uses between 100 and 150 Watt also when batteries are empty and PV Level is at zero. My hope: to find a way to send the SPH into standby mode via iobroker and hopefully then he needs less energy for its own

**Comment by PLCHome** [comment]
If you look at the data, you will see that the Accu is charged with the energy and also discharged after a while. Growatt does this to protect the batterys. I don't think you can swich the inverter on standby.

You are welcome to make a note of the procedure in the browser (F12). 

Then you can copy it too. But at your own risk.

**Comment by iobroker99** [comment]
the problem isn´t a toggle between charging / discharging, but the very high self usage in a typical "standby" position (battery empty, no PV power) but without falling into real standby. compared with Solis, SMA ecc Growatt needs double or tripple amount of energy for its own. Photovoltaikforum is full with discussions about that
but it seems that it´s really not possible to bring it manually into standby, got response from Growatt :-(

**Comment by PLCHome** [comment]
I can't help you here, it's a Growatt problem.
I can program something that sets the parameters like in the web interface. I do not know something from a switch for the operating mode there. If ther is one, let me know.
However, the inverter does not consume 150w, just take a look at the charging power from the Grid.

It switches between PV Batt and Batt. For me, 150W of the 153W go into the battery. The energy is discharged again after about 6 hours, of course it is not effective. Actually, the declaration of conformity says that no electricity is taken from the grid for charging.

![image](https://user-images.githubusercontent.com/29116097/145021410-1ec05ad3-8dce-40e4-b767-3c23db86ca68.png)

You can translate the state. Change the <ID>
```
{
  "0_userdata.0.Growatt.Status": {
    "from": "system.adapter.admin.0",
    "user": "system.user.admin",
    "ts": 1614120413608,
    "common": {
      "name": "Value",
      "role": "",
      "type": "string",
      "desc": "Manuell erzeugt",
      "def": "",
      "read": true,
      "write": true,
      "custom": {
        "sql.0": {
          "enabled": true,
          "changesOnly": true,
          "debounce": 0,
          "maxLength": 10,
          "retention": "31536000",
          "changesRelogInterval": 0,
          "changesMinDelta": 0,
          "storageType": "",
          "aliasId": "",
          "counter": false
        }
      }
    },
    "native": {},
    "acl": {
      "owner": "system.user.admin",
      "ownerGroup": "system.group.administrator"
    },
    "_id": "0_userdata.0.Growatt.Status",
    "type": "state"
  }
}
```

```
function dialog_mixHistory_getStatusText(status){
    if(status==0){
        return "Standby";
    }else if(status==1){
        return "Checking";
    }else if(status==3){
        return "Fault";
    }else if(status==4){
        return "Flash";
    }else if(status==5){
        return "PV Bat Online";
    }else if(status==6){
        return "Bat Online";
    }else if(status==7){
        return "PV Bat Offline";
    }else if(status==8){
        return "Bat Offline";
    }else if(status==8){
        return "Bypass";
    }else{
        return "Unknown "+status;
    }
}

on({id: 'growatt.0.<id>.devices.<id>.historyLast.status'/*status*/, change: "ne"}, async function (obj) {
  var value = obj.state.val;
  setState('0_userdata.0.Growatt.Status'/*Status*/, dialog_mixHistory_getStatusText(value));
});

```

**Comment by iobroker99** [comment]
seems to be a problem with newer Growatts, but yes - its a Growatt problem. thank you! If I find out more I give you an update

**Comment by iobroker99** [comment]
have you tried to use a cloud forecast for that?
