### ISSUE TITLE
Timeout Error

### ISSUE THREAD

**Issue by Dreistein19** [PLCHome/ioBroker.growatt#16]
Hi,

Is it possible, to make the Timeout configurable ?
So we can try any other Timeout e.g. 6.000 ms.
Today the adapter won't runnig with an Timeout of 5.000 ms.

**Comment by PLCHome** [comment]
I'll have a look. I am currently testing to keep the session and not to log in to the website every 30 seconds. But the problem is that I am logged out at different times.

**Comment by Pandia22** [comment]
Hi, 
thank you for the great adapter. Unfortunately, this has two major weaknesses:

1st: At timeout = 5.000 ms I get about 80 - 100 error messages in the log file. Can timeout be increased to e.g. 10.000 ms? Better still make the parameter configurable.
2nd: In the error log messages the Growatt server password is output unencrypted. Is it not possible to put a mask on it?

**Comment by PLCHome** [comment]
>> 2nd: In the error log messages the Growatt server password is output unencrypted. Is it not possible to put a mask on it?

It is implemented as required in the best practice example

>> if you need to store passwords please encrypt them in Admin! You can check e.g. Apollon77/iobroker.meross for example code in index_m.html and main.js
https://github.com/ioBroker/ioBroker.repositories#development-and-coding-best-practices

```
            if (!this.supportsFeature || !this.supportsFeature('ADAPTER_AUTO_DECRYPT_NATIVE')) {
                if (obj && obj.native && obj.native.secret) {
                    this.config.password = this.decrypt(obj.native.secret, this.config.password);
                    this.config.shareKey = this.decrypt(obj.native.secret, this.config.shareKey);
                } else {
                    this.config.password = this.decrypt('Zgfr56gFe87jJOM', this.config.password);
                    this.config.shareKey = this.decrypt('Zgfr56gFe87jJOM', this.config.shareKey);
                }
            }
```

Unfortunately, I don't know how the feature ADAPTER_AUTO_DECRYPT_NATIVE is activated or deactivated.

**Comment by PLCHome** [comment]
done 1.1.2
