### ISSUE TITLE
Add additional plants to read status data

### ISSUE THREAD

**Issue by yunagear** [PLCHome/ioBroker.growatt#2]
Hi PCL,

thanks for your work, great adapter!
I added the adapter to iobroker and I'm getting all needed values from plant data. But not the status data for my inverter.
Is it possible to add additional inverters for status data?
we have a Growatt 1500-S inverter (Mode: A0B0D1ToPFU1MAS1, Build: G.1.8, Version: ggaa0404) with data logger ShineWIFI-S (Firmware: 1.7.7.7).
Goal is to use the data for our Grafana Dashboard.
Very apreciate your help.

Cheers
yunagear

**Comment by PLCHome** [comment]
I only have one inverter with a memory and I therefore need your help.
The entire module is a hack
Please log in to the https://server.growatt.com/ page
It's best to use chrome, press "F12" on the keyboard
Goto Network and press "F5"
Now you can filter on get
Please search for the get command that contains the data you are missing
![image](https://user-images.githubusercontent.com/29116097/98384968-b9b33700-204e-11eb-8b78-27b0b77e33c8.png)

I need the method and the url
![image](https://user-images.githubusercontent.com/29116097/98385284-1878b080-204f-11eb-92e2-a2571b2019ba.png)

Then I can try to extend the API

**Comment by yunagear** [comment]
Thank's for reply.
That's interesting as I have no "getMIXStatusData".
Instead I've found "getInvDayChart"
![growatt_daystatus](https://user-images.githubusercontent.com/74056948/98474493-a8585f00-21f5-11eb-85ae-709156c8b736.PNG)

![growatt_method](https://user-images.githubusercontent.com/74056948/98474972-d89ffd80-21f5-11eb-83d9-42728dc02bc9.PNG)

Seems that it's a predefined counter (0-287) for the values, so updated aprox 12 mins.
Not easy to parse:(

And sorry wanted to say ...PLC not PCL of course:)

**Comment by PLCHome** [comment]
If there is no "getINVStatusData", it is not that easy to get the current value.

If I would just take the last value that is not zero, it can happen that the value remains.
If I look for the value based on the time, the next one whines with a time lag.

I'll check. I think the best is the last value that is not zero and calculate the time.

**Comment by PLCHome** [comment]
You can find the current grid feed under "deviceData" "pac".
A few w are missing here because the power loss of the inverter has been subtracted here.

**Comment by yunagear** [comment]
Very cool!
Thank's for support. It's also ok for us to have fixed time values for update (eg. every 30 mins).
Hope it's not to much work, if so let me know plz.
As this is one of our first plants in Croatia you can have acces if needed of course (it's running since 2 weeks).

**Comment by PLCHome** [comment]
I have added a get..ChartLast for the last diagram value in the API for Inv / MIX / TLX, all others have the current status. 
Since I somehow can't get into the publish from ioBroker, I didn't want to adapt the adapter now. 
But you can test it by updating the API 0.0.3 ist named "growatt" by npm. 

I would appreciate your feedback.

**Comment by PLCHome** [comment]
If you modify the options in the API you can also get a string or array with all values.
I will do this later in the ioBroker using checkboxes

**Comment by yunagear** [comment]
sorry not so familliar with npm is npm -g update growatt enough?
cause i see no additional values in iobroker after reloading the adapter.

**Comment by PLCHome** [comment]
I have no idea either. The adapter is inside. I'll publish it when I have time

**Comment by PLCHome** [comment]
done

**Comment by yunagear** [comment]
cool now it worked:) currently pac value is 0 ...but i have to check it tomorrow, as the growatt value is also filled with 'null' atm. let you know asap!

**Comment by yunagear** [comment]
Top! thx a lot man:)!!
![growatt_pac](https://user-images.githubusercontent.com/74056948/100587572-0823c080-32f1-11eb-8c2a-4331fea3e674.PNG)

**Comment by PLCHome** [comment]
@yunagear

Would be nice if you could test the adapter so that I can get into the stable (default) with 0.0.12.
I need your comment for 0.0.12 here:

[https://forum.iobroker.net/topic/36474/test-adapter-growatt-v0-0-12](https://forum.iobroker.net/topic/36474/test-adapter-growatt-v0-0-12)

**Comment by PLCHome** [comment]
@yunagear
@kopierschnitte

I found a way to set the data logger interval from 5 minutes to 1 minute.
Maybe this is something for you too.
---------
Remove the rubber plug of the KEY button from ShineWiFi-S, and short press the button inside. The blue LED
will light up. Use your phone or computer to connect to the wireless network emitted by the
ShineWiFi-S module. The network name/SSID is the serial number of the ShineWiFi-S
module.

**Login Page**
After the connection is successfully established, open the web browser on your phone or
computer and type 192.168.10.100 in the address bar. The username is admin, the
default password is 12345678.
![image](https://user-images.githubusercontent.com/29116097/104449903-9ef5c500-559f-11eb-8279-6c5ec6295db4.png)

**Advanced Settings**
Change the data interval time to 1 minute
![image](https://user-images.githubusercontent.com/29116097/104450032-c9e01900-559f-11eb-9166-7b9a2fdd7d5b.png)

**System Restart**
Restart your ShineWiFi-S module on this page, click “Restart Immediate” to
enable the new settings you just made and logout from the internal webserver of your
ShineWiFi module.
![image](https://user-images.githubusercontent.com/29116097/104450177-f4ca6d00-559f-11eb-83cb-56678c12144a.png)

On the left the data from yesterday is still every 5 minutes and on the right from today is every 1 minute
![image](https://user-images.githubusercontent.com/29116097/104449013-3eb25380-559e-11eb-99f0-bd1b86c3bf28.png)

Unfortunately the chart seems to work every 5 minutes. Maybe you can check that out. Then we would have to find a solution.

**Comment by kopierschnitte** [comment]
Interesting. Thanks for sharing. I've adjusted the interval and it seems the values get updated more frequently!
