### ISSUE TITLE
Growatt Login: Error: The server sent an unexpected response: /error.do?errorMess=errorNoLogin

### ISSUE THREAD

**Issue by Toysman** [PLCHome/ioBroker.growatt#22]
**Describe your inverter**

Typ, modell, ...  GroWatt Mic 600 TL-X
The enviroment (panels, accu etc.) Trina Solar TSM 395
The modell of the logger Growatt Shine X

**Describe the bug**  
The adapter has intermittent problems logging in to Growatt. I have worked in the settings with the key as well as with username and password.
Until the adapter is restarted, no further connection to Growatt is possible and the "Connection to service or device" gets a yellow triangle.

**To Reproduce**  

2. Click on '...'

**Expected behavior**  

**Screenshots & Logfiles**  
If applicable, add screenshots and logfiles to help explain your problem.

**Versions:**

- Adapter version: <1.1.9>
- JS-Controller version: <4.0.21> 
- Node version: <14.18.3> 
- Operating system: <ioBroker>

**Additional context**  
<img width="869" alt="Bildschirmfoto 2022-03-31 um 18 11 29" src="https://user-images.githubusercontent.com/76917387/161102037-808e26b0-85ef-45c7-8a49-424746968285.png">
<img width="2126" alt="Bildschirmfoto 2022-03-31 um 18 11 50" src="https://user-images.githubusercontent.com/76917387/161102041-1fc5eafc-a730-456b-875f-2b9d2c4b519a.png">

**Comment by Toysman** [comment]
Hello,
I have changed the login procedure to username and password, but still keep getting error messages in the logs from ioBroker
<img width="1023" alt="Bildschirmfoto 2022-04-01 um 15 52 12" src="https://user-images.githubusercontent.com/76917387/161278002-53ba3a3f-5b31-4fdd-9c56-01b43db50eb6.png">
.

**Comment by PLCHome** [comment]
But you should now get data.
The website will log you out after a while. The adapter still logs this as a warning.
I have to see how I can better distinguish this from other errors.
However, the adapter instance should not be constantly yellow. It should turn green.

It is possible to log in again each time, but this does not work properly either.

If you now get data, your key is outdated.
