### ISSUE TITLE
mTotal is missing with V1.1.12

### ISSUE THREAD

**Issue by Homeworker11** [PLCHome/ioBroker.growatt#23]
After upgrade to Growat Adapter V1.1.12 the field mTotal is missing. It was the total savings in Euro.
In the old Vers. it was in
growatt.0.340069.devices.DHE3A11050.totalData.mTotal

**Comment by PLCHome** [comment]
fine.
I need the type `growatt.0.340069.devices.DHE3A11050.deviceData.deviceTypeName`
Are some values ​​updated in this area?
growatt.0.340069.devices.DHE3A11050.totalData
Are some values ​​updated in other areas?
growatt.0.340069.devices.DHE3A11050....


Is the instance yellow?
Is there something in the log about this value?

**Comment by PLCHome** [comment]
in my case your the total savings in Euro is stored in 
growatt.0.340069.devices.DHE3A11050.totalData.photovoltaicRevenueTotal

or a day:
growatt.0.340069.devices.DHE3A11050.totalData.photovoltaicRevenueToday

**Comment by Homeworker11** [comment]
Here is a screenshot of the actual device tree. 

 

In the older version the tree has different name:

 

“growatt.0.340069.devices.DHE3A11050.totalData.mTotal”

 

With the new version of the adapter the name of the tree “totalDate” changed to “deviceData” 

And the old tree was not updated with new data.

I tried to change this name back to “totalData” but without success.

 

Next step was I deleted the old tree und use the new one.

And in this new tree my mTotal field is not three anymore.

 

The instance is green.

Nothing special in the log:

 

 



 

Von: PLCHome ***@***.***> 
Gesendet: Freitag, 8. April 2022 16:57
An: PLCHome/ioBroker.growatt ***@***.***>
Cc: Homeworker11 ***@***.***>; Author ***@***.***>
Betreff: Re: [PLCHome/ioBroker.growatt] mTotal is missing with V1.1.12 (Issue #23)

 

fine.
I need the type growatt.0.340069.devices.DHE3A11050.deviceData.deviceTypeName
Are some values ​​updated in this area?
growatt.0.340069.devices.DHE3A11050.totalData
Are some values ​​updated in other areas?
growatt.0.340069.devices.DHE3A11050....

Is the instance yellow?
Is there something in the log about this value?

**Comment by Homeworker11** [comment]
I don’t have this fields.

 

It is not a big deal. I can calculate the missing savings directly in VIS or in Blockly

 

 

 

Von: PLCHome ***@***.***> 
Gesendet: Freitag, 8. April 2022 17:13
An: PLCHome/ioBroker.growatt ***@***.***>
Cc: Homeworker11 ***@***.***>; Author ***@***.***>
Betreff: Re: [PLCHome/ioBroker.growatt] mTotal is missing with V1.1.12 (Issue #23)

 

in my case your the total savings in Euro is stored in
growatt.0.340069.devices.DHE3A11050.totalData.photovoltaicRevenueTotal

or a day:
growatt.0.340069.devices.DHE3A11050.totalData.photovoltaicRevenueToday

**Comment by PLCHome** [comment]
sorry, no picture, your answer is not readible

**Comment by Homeworker11** [comment]
Here is a screenshot of the actual device tree. 

In the older version the tree has different name:

“growatt.0.340069.devices.DHE3A11050.totalData.mTotal”

With the new version of the adapter the name of the tree “totalDate” changed to “deviceData” 
And the old tree was not updated with new data.
I tried to change this name back to “totalData” but without success.

Next step was I deleted the old tree und use the new one.
And in this new tree my mTotal field is not three anymore.
![image](https://user-images.githubusercontent.com/74406135/162478231-94a90abf-7659-44ad-83dc-a8e619f9b696.png)

The instance is green.
Nothing special in the log:

**Comment by PLCHome** [comment]
A brief explanation of how it works. This module reads the API of the website. This is maintained by Growatt for their website. And growatt is not interested in anyone who wants to read the data.
The API responds with a JSON object. This has attributes with the values.
The adapter creates iobroker objects for these attributes.

If Growatt changes something on his side, attributes can disappear or be added.

However, I have redesigned reading from the website. It is not possible for a single attribute to be missing. But if an area is missing then I made a programming error.

I'll take a look at reading inv on a demo system and compare it to the old code when I have time.

**Comment by Homeworker11** [comment]
Thanks.
For me it is a bit strange that the tree name was changed with this update to V1.1.12.
In the past updates does not changed annything in the tree.

**Comment by PLCHome** [comment]
You are right, your inverter is missing in this case.
Inverter type:


```
        if (device.obj.mix) {
          growattTyp = MIX;
        } else if (device.obj.max) {
          growattTyp = MAX;
        } else if (device.obj.spa) {
          growattTyp = SPA;
        } else if (device.obj.hps) {
          growattTyp = HPS;
        } else if (device.obj.tlx) {
          growattTyp = TLX;
        } else if (device.obj.storage) {
          growattTyp = STORAGE;
        }

```
must be:
```
        if (device.obj.mix) {
          growattTyp = MIX;
        } else if (device.obj.max) {
          growattTyp = MAX;
        } else if (device.obj.spa) {
          growattTyp = SPA;
        } else if (device.obj.inv) {
          growattTyp = INV;
        } else if (device.obj.hps) {
          growattTyp = HPS;
        } else if (device.obj.tlx) {
          growattTyp = TLX;
        } else if (device.obj.storage) {
          growattTyp = STORAGE;
        }

```
Total data and history are missing

I will fix it

**Comment by PLCHome** [comment]
done

**Comment by Homeworker11** [comment]
Perfekt Danke !
