### ISSUE TITLE
 Apple devices cannot open the adapter's config page with Safari, all values ​​are empty

### ISSUE THREAD

**Issue by PLCHome** [PLCHome/ioBroker.growatt#25]
From Wildbill
magix said in Test Adapter Growatt v1.0.0:

I noticed when I go back to the adapter settings that all fields are empty again and no more ticks can be set below.
Is that normal?
Is there a way to get the voltage readings?

I noticed the exact same problem today. When I open the adapter's config page with Safari on any of my Apple devices, all the values ​​are empty. This is the case on two Macs as well as on the IPad and IPhone. If I open the config pages of other adapters, I can operate everything normally. If I open the config page of the Growatt adapter with Firefox on the Mac, all the values ​​are there and I can operate everything.
So the problem is only the configuration page of the Growatt adapter in connection with Safari. Everything else works.
Content blockers are disabled, but they can't really be anything if the other sites work.
What is different about the Growatt adapter or where can I start? Can someone test with Apple hardware whether it's the same with Safari?
Greetings, Juergen

**Comment by Wildbill-Z** [comment]
Seems to be [solved](https://forum.iobroker.net/post/796568) with 1.1.15
I tested both, Safari on Mac and iPad and both are showing the admin correctly and with the possibility to change values.
