### ISSUE TITLE
Growatt exception: AxiosError: Request failed with status code 588

### ISSUE THREAD

**Issue by Homeworker11** [PLCHome/ioBroker.growatt#28]
Adapter V 1.1.17
After Update to Admin 6.2.17
I get new error massages.
![image](https://user-images.githubusercontent.com/74406135/187032058-57118d87-c96a-4efd-8843-ad2ffe19743c.png)

**Comment by gerdluthe** [comment]
Hab den Fehler auch
Admin v6.2.17
Growatt Adapter v1.1.17

**Comment by sch0l0ka** [comment]
Same problem since yesterday

**Comment by Pandia22** [comment]
It seems to be a general problem of the adapter. Growatt server can be reached via WWW without any problems. 
Growatt: V1.1.17

**Comment by Toysman** [comment]
muss leider ebenfalls den Fehler bestätigen...

Admin 6.2.17
Node.js 16.17.0
NPM 8.15.0
Growatt 1.1.17

teilweise innerhalb kurzer Zeit +99 Protokolleinträge vom Growatt Adapter

![Bildschirmfoto 2022-08-29 um 17 03 36](https://user-images.githubusercontent.com/76917387/187232511-81d27f70-3ff7-4f55-900c-edbc32ad7a2f.png)

**Comment by chucky6661902** [comment]
Hallo 
Auch ich habe das Problem 

Admin 5.3.8 ( also kein Admin Problem) 

Ich hoffe es geht zu fixen

**Comment by MadTrinity** [comment]
Hallo,
Bei mir auch das selbe Problem.
Admin v6.2.17

**Comment by PLCHome** [comment]
Fixed in last Version

**Comment by nobbiman** [comment]
Das Problem besteht leider immer noch. Ich bekomme täglich 99 Meldungen!
Geht da noch was?

**Comment by PLCHome** [comment]
Version?
  
  
  
  
  
  
  

  
  
>
