### ISSUE TITLE
lost datafields after upgrade with a battery system Min2500XH

### ISSUE THREAD

**Issue by cracyfloyd** [PLCHome/ioBroker.growatt#30]
**Describe your inverter**

Growatt Min2500XH
Arc XH Battery 7kw
shine wifi

**Describe the bug**  
After i upgrade my inverter with a xh battery system i lost some data fields.

this datafields i only see in iobroker now. 

![01](https://user-images.githubusercontent.com/57620791/217074878-d4a8cbc0-7569-405e-90fd-fe77ab02b4f4.jpg)
![02](https://user-images.githubusercontent.com/57620791/217075051-48429d42-aee6-440e-afac-3d0be849f583.jpg)

**Comment by PLCHome** [comment]
I don't have this inverter. I can't answer why the data disappears.
With my inverter (SPH4000) everything is OK.
I have no way of testing either. The API for your inverter is created with experience values. She has not been tested.
