### ISSUE TITLE
Ähnliches Problem

### ISSUE THREAD

**Issue by Chrissili** [PLCHome/ioBroker.growatt#31]
Hallo PLCHome, leider weiß ich nicht wie ich am besten Kontakt mit Dir aufnehmen kann und ich bin auch neu in Github, bin aber auf dich gestoßen, weil ich exakt das Problem habe, die Werte meines Growatt Wechselrichters abzugreifen und ich glaube Du könntest mir helfen. Habe versucht über Python mir was zu basteln, komme aber nicht weiter...
Ohne Dich zu belästigen und man kann das hier natürlich auch sofort dann löschen, aber wie kann ich Dich kurz dazu befragen, wo ich die speziellen Werte für meinen Growatt-Account erhalte? Bislang habe ich nur Gesamtwerte wie über response = session.post("https://server.growatt.com/selectPlant/getPlantList", data={"currPage": "1","plantType": "-1","orderType": "2","plantName": "".) Wäre Dir super dankbar, Chrissili

**Comment by PLCHome** [comment]
Aktuell nutzt die API /index/getPlantListTitle
https://github.com/PLCHome/growatt/blob/46a5ed43ad5a4676e0a718110c21bf6c74140ab4/lib/growatt.js#L287

Der Code zur Abfrage ist ausgelagert.
Vielleicht kannst du ihn ja übersetzen.
https://github.com/PLCHome/growatt/blob/master/lib/growatt.js

**Comment by Chrissili** [comment]
Danke Dir, das hat mir schon sehr weitergeholfen. Aber kommt man mit diesem growatt.js auch an die "live Werte"?  PV Erzeugung, Batterieprozentsatz und Netzverbrauch? oder brauche ich da ein anderes Skript bzw. anderen Pfad? Wäre toll, wenn Du mir da nochmal kurz weiterhelfen könntest...

**Comment by PLCHome** [comment]
Also bei meinem SPH4000 funktioniert das mit den Livewerten.
Es gibt zwei Möglichkeiten einmal über die Statusanzeige und über die historischen Daten.
Beim Max ging es nur über die historischen Daten, der gibt die auch in der Webansicht nicht aus, sondern zeigt die Erzeugung nur als Graph an.

**Comment by PLCHome** [comment]
Am einfachsten ist es wahrscheinlich, sich die Daten mit Grott zu holen.

**Comment by Chrissili** [comment]
ja ich nutze "MAX" das heißt ich müsste es über: response = session.post("https://server.growatt.com/device/getMAXHistory", data={"typ": "MAX","sn": "abc","startDate": "2023-02-28", "endDate": "2023-02-28"}) erhalten?
Mit was muss man denn da 'start:', start, 'allDatasets:', allDatasets belegen?

**Comment by Chrissili** [comment]
ah habs sorry jetzt bin ich glücklich - danke

**Comment by PLCHome** [comment]
```
[MAX]: {
    snParam: 'maxSn',
    getTotalData: '/panel/max/getMAXTotalData',
    getHistory: '/device/getMAXHistory',
  },
...
getHistory(typ, sn, startDate, endDate, start, allDatasets) {
  const params = new Url.URLSearchParams({
          [GROWATTTYP[typ].snParam]: sn,
          startDate: startDate.toISOString().substring(0, 10),
          endDate: endDate.toISOString().substring(0, 10),
          start,
        });
...
      if (typeof options.historyAll === 'undefined') {
        options.historyAll = false;
      }
      if (typeof options.historyLastStartDate === 'undefined') {
        options.historyLastStartDate = new Date(new Date().setDate(new Date().getDate() - 1));
      }
      if (typeof options.historyLastEndDate === 'undefined') {
        options.historyLastEndDate = new Date(new Date().setDate(new Date().getDate() + 1));
      }
      if (typeof options.historyStart === 'undefined') {
        options.historyStart = 0;
      }
...
const historyLast = await this.getHistory(
                growattTyp,
                serialNr,
                options.historyLastStartDate,
                options.historyLastEndDate,
                options.historyStart,
                options.historyAll
              ).catch(e => {
                debugApi(`getAllPlantDeviceData getHistory ${growattTyp} err:`, e);
                reject(e);
              });
```
also bei MAX in json für den 1.3.2023:
```
{"maxSn": <xxx>,
"startDate": "2023-02-28",
"endDate": "2023-03-02",
"start": 0
}
```

**Comment by Chrissili** [comment]
sorry zu früh gefreut... kann das sein als ergebnis?! {'endDate': '2023-03-02', 'datas': [], 'totalPageSize': 0, 'haveNext': False}

**Comment by Chrissili** [comment]
ich glaub es liegt an dem "maxSn" oder "sn"...
was muss man da genau an Wert angeben? "maxSn": "ABC8CCU00S" oder nicht?
wobei ich jetzt DeviceType "Storage" gesehen habe als doch nicht "MAX" dann?

**Comment by Chrissili** [comment]
jetzt hab ichs wirklich - sorry für die störung
