### ISSUE TITLE
Synchronization of History Data

### ISSUE THREAD

**Issue by nt-ru** [PLCHome/ioBroker.growatt#32]
--- English below ---

Hallo,
vielen Dank erstmal für diesen tollen Adapter! Habe ihn erfolgreich am Laufen zusammen mit InfluxDB/Grafana.
Ein Problem jedoch, was ich mit den so gewonnenen Daten habe ist, dass sie mal mehr, mal weniger lückenhaft sind. Das kommt durch eine instabile WiFi Verbindung, was sowohl meinen Homeserver, als auch den Logger vom Inverter betrifft. In der Growatt Weboberfäche, bzw. auch in der App stelle ich fest, dass Datenlücken (wenn z.B. der Logger einen Tag lang keine Internetverbindung hatte) automatisch nachsynchronisiert und gefüllt werden, sobald der Logger wieder eine Verbindung hat.
Dieses Verhalten würde ich gerne mit dem ioBroker Adapter auch realisieren. Frage: Ist dies überhaupt möglich? Es gibt ja zumindest API Kommandos dafür und die "HistoryLast" Option macht schon etwas Hoffnung, kann ja aber keine vergangenen Daten liefern.
Mein Wunsch wäre, einen Button "Synchronize All" zu haben, der bis zu einem wählbaren Startzeitpunkt (Option), z.B. seit Start der Anlage, alle Daten synchronisiert - das wäre zur einmaligen, manuellen Ausführung. Und zum zweiten einen Button "Synchronize Recent", der einen kürzeren Zeitraum synchronisiert (z.B. automatisch 1x am Tag den letzten Tag, oder manuell: letzte Stunde).
Oder ist das gar nicht möglich, wäre dann [https://github.com/PLCHome/growatt](https://github.com/PLCHome/growatt) die richtige Adresse, Daten manuell holen mit Requests und anschließend Daten manuell zur influxDB hinzufügen?

Danke schon mal für eine Erklärung / Einschätzung!

---

Hello,
thanks a lot for this great adapter! I have it successfully running in an InfluxDB/Grafana setup.
However, one problem I face with the obtained data is that it is sometimes more, sometimes less patchy. This is due to an unstable WiFi connection, which affects both my home server and the logger from the inverter. In the Growatt web interface and in the app, I notice that data gaps (e.g. if the logger has not had an internet connection for a day) are automatically synchronized and filled as soon as the logger has a connection again.
I would like to realize this behavior with the ioBroker adapter as well. Question: Is this possible at all? There are at least API commands for this and the "HistoryLast" option gives some hope, but but it's name is misleading since it is not meant to provide past data, as I have read.
My wish would be to have a button "Synchronize All", which synchronizes all data up to a selectable start time (option), e.g. since start of the plant - this would be for a one-time, manual execution. And secondly a button "Synchronize Recent", which synchronizes a shorter period (e.g. automatically once a day the last day, or manually: last hour).
Or is that not possible at all, would [https://github.com/PLCHome/growatt](https://github.com/PLCHome/growatt) be the right address then, get data manually with requests and then add data manually to influxDB?

Thanks already for an explanation / estimation!

**Comment by PLCHome** [comment]
Auf Anfrage habe ich den Historybefehl schon erweitert. Es ist möglich, die Historie über einen Zeitbereich abzufragen.
Das Problem ist mehr, die Daten in einer Datenbank abzulegen. Dazu müsste dieses für den Influx und SQL Adapter speziell implementiert werden, eine Funktion im ioBroker die dieses adapterunabhängig nachspielen kann, ist mir nicht bekannt.
 Vielleicht gibt es diese.
Speziell der SQL-Adapter reagiert allergisch auf doppelte Zeitpunkte. Influx setze ich nicht mehr ein, weil ich massive Probleme hatte, ab einer gewissen Datenmenge hat die DB die CPU aufgefressen. 

Den Zeitpunkt der letzten Abfrage könnte sich der Adapter in einem Objekt merken. Dann die Daten ab zu fragen ist möglich.
Prinzipiell spricht nichts dagegen, das es jemand umsetzt. 


----------------

On request I have already extended the history command. It is possible to query the history over a time range.
The problem is more about storing the data in a database. To do this, this would have to be specially implemented for the Influx and SQL adapter, I do not know of a function in ioBroker that can reproduce this adapter-independently.
  Maybe there is.
The SQL adapter in particular reacts allergically to double points in time. I no longer use Influx because I had massive problems, from a certain amount of data the DB ate up the CPU.

The adapter could note the time of the last query in an object. Then querying the data is possible.
In principle, there is nothing wrong with someone implementing it.

**Comment by PLCHome** [comment]
### getHistory

This command lists the history. It can be used, for example, to supplement data in a database.
Regardless of the time range, Growatt always seems to return 80 records. If the interval is set to 1 minute and more than 80 minutes are needed, the command must be executed several times and the start from 0 must be increased more and more.

| Parameter | Type    | Description                                                                                      |
| --------- | ------- | ------------------------------------------------------------------------------------------------ |
| type      | String  | The type of inverter can be found in object "growatt. - instance - . - nr - .devices. - sn - .growattType".  |
| sn        | String  | The serialnumber of inverter can be found in object path "growatt. - instance - . - nr - .devices. - sn - ". |
| startDate | Date    | The atart                                                                                        |
| endDate   | Date    | The end mast be grater then start                                                                |
| start     | Integer | 0 is the start page for the call with the most recent data first                                 |

Example call:

```
  sendTo('growatt.0','getHistory',{"type":"<your inverter type>","sn":"<your inverter serial>","startDate":new Date((new Date()).getTime()- 60*60*1000),"endDate":new Date() , "start":0},(res)=>{console.log(res)})
```

Example code:

```
const sn = " your sn "; //your inverter sn 
const inType = " your typ "; // the invertertyp
const hist = 'growatt.0. your nr .devices. your sn .historyLast.'; // the Path to history
const storeField =['accChargePower','etoGridToday']; //the fields to store
const history = "influx.0" //your History sql.0 or influx.0 or history.0 ...
const min = 10 // größer 10 min auffüllen....

on({id: hist+'calendar', change: "ne"},(obj)=>{
    if ((obj.state.val - obj.oldState.val) > min*60000) {
        console.log(obj.state.val - obj.oldState.val);
        function fillup(res) {
            res.forEach((r)=>{
                const ti = (new Date(r.calendar)).getTime();
                if (ti > obj.oldState.val && ti < obj.state.val) {
                    function store(n) {
                        sendTo(history, 'storeState', {
                            id: hist+n,
                            state: {ts: ti, val: r[n], ack: true}
                        }, result => {console.log(`added ${hist+n} ${new Date(ti)} ${r[n]}`)});
                    }
                    storeField.forEach((f) => {store(f)});
                }
            })
        }
        sendTo('growatt.0','getHistory',{"type":inType,"sn":sn,"startDate":obj.oldState.val,"endDate":obj.state.val, "start":0},fillup)
        sendTo('growatt.0','getHistory',{"type":inType,"sn":sn,"startDate":obj.oldState.val,"endDate":obj.state.val, "start":1},fillup)
        sendTo('growatt.0','getHistory',{"type":inType,"sn":sn,"startDate":obj.oldState.val,"endDate":obj.state.val, "start":2},fillup)
        sendTo('growatt.0','getHistory',{"type":inType,"sn":sn,"startDate":obj.oldState.val,"endDate":obj.state.val, "start":3},fillup)
    }
});
```
