### ISSUE TITLE
Kein Datenlogger gefunden

### ISSUE THREAD

**Issue by Denn281** [PLCHome/ioBroker.growatt#34]
Adapter findet keinen Datenlogger 

Getestet habe ich  Version 3.0.2 und Versoin 3.0.4.

Wechselrichter: MIC 2000TL-X
Datenlogger: Growatt ShineWIFI-X
Node.js: v18.16.0
NPM: 9.5.1

Log:

`
growatt.0 | 2023-08-03 14:06:31.147 | debug | getDatalogger: []
-- | -- | -- | --
growatt.0 | 2023-08-03 14:06:31.058 | debug | Enter lifeSignCallback 600000ms
growatt.0 | 2023-08-03 14:06:31.057 | debug | {"command":"getDatalogger","message":"{}","from":"system.adapter.admin.0","callback":{"message":"{}","id":56,"ack":false,"time":1691064391054},"_id":66164946}
growatt.0 | 2023-08-03 14:06:22.139 | debug | Leave growattData :89ms
growatt.0 | 2023-08-03 14:06:22.138 | debug | Growatt time for parseData : 0ms
growatt.0 | 2023-08-03 14:06:22.136 | debug | Growatt time for allPlantData : 86ms
growatt.0 | 2023-08-03 14:06:22.051 | debug | Enter lifeSignCallback 600000ms
growatt.0 | 2023-08-03 14:06:22.050 | debug | Growatt isConnected() : true
growatt.0 | 2023-08-03 14:06:22.050 | debug | Enter lifeSignCallback 600000ms
growatt.0 | 2023-08-03 14:06:22.049 | debug | Enter growattData, Param: sessionHold:true
growatt.0 | 2023-08-03 14:06:19.437 | debug | getDatalogger: []
growatt.0 | 2023-08-03 14:06:19.348 | debug | Enter lifeSignCallback 600000ms
growatt.0 | 2023-08-03 14:06:19.347 | debug | {"command":"getDatalogger","message":"{}","from":"system.adapter.admin.0","callback":{"message":"{}","id":55,"ack":false,"time":1691064379343},"_id":66164945}
growatt.0 | 2023-08-03 14:06:16.637 | debug | getDatalogger: []
growatt.0 | 2023-08-03 14:06:16.548 | debug | Enter lifeSignCallback 600000ms
growatt.0 | 2023-08-03 14:06:16.548 | debug | {"command":"getDatalogger","message":"{}","from":"system.adapter.admin.0","callback":{"message":"{}","id":54,"ack":false,"time":1691064376544},"_id":66164944}
growatt.0 | 2023-08-03 14:06:10.630 | debug | getDatalogger: []
growatt.0 | 2023-08-03 14:06:10.536 | debug | Enter lifeSignCallback 600000ms
growatt.0 | 2023-08-03 14:06:10.535 | debug | {"command":"getDatalogger","message":"{}","from":"system.adapter.admin.0","callback":{"message":"{}","id":53,"ack":false,"time":1691064370532},"_id":66164943}
growatt.0 | 2023-08-03 14:06:08.516 | debug | getDatalogger: []
growatt.0 | 2023-08-03 14:06:08.424 | debug | Enter lifeSignCallback 600000ms
growatt.0 | 2023-08-03 14:06:08.424 | debug | {"command":"getDatalogger","message":"{}","from":"system.adapter.admin.0","callback":{"message":"{}","id":52,"ack":false,"time":1691064368414},"_id":66164942}
growatt.0 | 2023-08-03 14:05:57.146 | debug | getDatalogger: []
growatt.0 | 2023-08-03 14:05:57.056 | debug | Enter lifeSignCallback 600000ms
growatt.0 | 2023-08-03 14:05:57.054 | debug | {"command":"getDatalogger","message":"{}","from":"system.adapter.admin.0","callback":{"message":"{}","id":51,"ack":false,"time":1691064357048},"_id":66164941}
growatt.0 | 2023-08-03 14:05:53.416 | debug | Leave growattData :1367ms
growatt.0 | 2023-08-03 14:05:53.412 | debug | Growatt time for parseData : 0ms
growatt.0 | 2023-08-03 14:05:53.410 | debug | Growatt time for allPlantData : 131ms
growatt.0 | 2023-08-03 14:05:53.281 | debug | Enter lifeSignCallback 600000ms
growatt.0 | 2023-08-03 14:05:53.278 | debug | Growatt time for login : 1229ms
growatt.0 | 2023-08-03 14:05:53.276 | debug | Growatt isConnected() : true`

Kann mir jemand sagen was ich falsch mache ?

**Comment by PLCHome** [comment]
Entweder wird der Typ des MIC 2000TL-X nicht unterstützt oder es liegt ein Fehler in der Cloud vor...
"Growatt time for parseData : 0ms" zeigt, dass er hier auch nix verarbeitet.
Gibt er unter "growatt.0.<xxx>.devices.<xxx>.growattType" einen Typen aus?

**Comment by Denn281** [comment]
Okay ich denke dann wird er nicht unterstützt, da ich es schon seit ein paar wochen immer mal wieder versucht habe.

Einen Typen gibt er leider auch nicht aus.
Er gibt nur unter dem Datenpunk Info Connection true aus.

**Comment by PLCHome** [comment]
Connectio ist true weil er sich zur Cloud verbinden kann.

Leider benötige ich hier deine Unterstützung. Melde dich an der Webseite an und Drücke F12 und Strg-R
Und dann bitte diese Nachricht suchen. Darin ist der Typ.

![image](https://github.com/PLCHome/ioBroker.growatt/assets/29116097/d765c02a-f711-449d-ae51-58a2daa7be73)

**Comment by PLCHome** [comment]
Eigentlich sollte der MIC aber funktionieren. Du bist aber auf dem richtigen Server?
Ich hatte schon mal jemanden, der sich einen US und einen deutschen Account angelegt hat.

**Comment by Denn281** [comment]
Also vlt stelle ich mich etwas blöd an, aber getDevicesByPlant kann ich nicht finden.

![getDevicesByPlant](https://github.com/PLCHome/ioBroker.growatt/assets/98456403/09964a20-c30f-46af-92a3-26505721b842)

**Comment by Denn281** [comment]
Angemeldet habe ich mich unter https://server.growatt.com.
Da kann ich auch alle Werte einsehen

**Comment by Denn281** [comment]
In getPlantListTitle steht: 
`id
: 
"*******"
logoImgName
: 
""
plantImgName
: 
"null"
plantName
: 
"Home12"
plantType
: 
"2"
timezone
: 
"2"
unit
: 
"€"`

**Comment by PLCHome** [comment]
Normalerweise muss danach mit der ID ein weiterer Aufruf erfolgen. Eigentlich getDevicesbyPlant

**Comment by Denn281** [comment]
Ich kann leider nur die Werte finden.


![get ](https://github.com/PLCHome/ioBroker.growatt/assets/98456403/626b0c9c-915e-4ba9-840e-05a2a2d817fe)

**Comment by PLCHome** [comment]
Komisch wenn ich mir das Bild links auf deinem Pic anschaue sieht es anders aus als in der Demoanlage, es ist schwarz....:
![image](https://github.com/PLCHome/ioBroker.growatt/assets/29116097/b99ae63d-4ab4-47a8-8d4c-679fef349415)

**Comment by PLCHome** [comment]
Sieht aus wie die Seite:
![image](https://github.com/PLCHome/ioBroker.growatt/assets/29116097/5ec3d8ad-7bf1-4d74-8ea5-b75e9ddac9fe)

Da ich so einen Inverter nicht habe, kann ich da nix machen. Alle Typen konnten nur umgesetzt werden, weil ich einen Key zum Testen bekommen habe.... Sorry

**Comment by Denn281** [comment]
Ja genau ich komme immer auf die „Schwarze“ Seite.
Vielen Dank schonmal für deine Mühe!
Ich würde dir auch einen Key zur Verfügung stellen, wenn Interesse besteht.

**Comment by PLCHome** [comment]
Gerne kannst du mir einen Key zukommen lassen, ich kann mir sie Calls der Seite einmal anschauen.

Das einfachste ist das Forum vom ioB und dan eine PN:
https://forum.iobroker.net/user/plchome-0

Ich bekomme seit einiger Zeit keine E-Mail wenn ich eine PN bekomme. Am besten noch eine kurzes Hallo im Thread
https://forum.iobroker.net/topic/36474/test-adapter-growatt-v3-0-0/541

**Comment by PLCHome** [comment]
Du musst die Box einschalten:
![image](https://github.com/PLCHome/ioBroker.growatt/assets/29116097/dbb1d82c-91f5-43f6-b542-1139c12bc202)
