### ISSUE TITLE
Growatt adapter errors in log

### ISSUE THREAD

**Issue by passuff** [PLCHome/ioBroker.growatt#38]
I'm getting these errors very frequently. Im Using Growatt adapter v3.2.1. 
The adapter seems to work but has frequntly issues to access the server.

`
growatt.0 | 2023-09-27 11:06:41.886 | warn | Login:{}
-- | -- | -- | --
growatt.0 | 2023-09-27 11:04:37.842 | warn | Login:{}
growatt.0 | 2023-09-27 11:02:33.739 | error | Growatt exception: Error: The server sent an unexpected response, a fatal error has occurred
growatt.0 | 2023-09-27 10:34:58.798 | error | Growatt exception: AxiosError: Request failed with status code 500
growatt.0 | 2023-09-27 10:32:23.006 | error | Growatt exception: AxiosError: Request failed with status code 500
growatt.0 | 2023-09-27 10:05:38.434 | error | Growatt exception: Error: {"result":-1}
growatt.0 | 2023-09-27 10:03:31.425 | error | Growatt exception: AxiosError: Request failed with status code 500
growatt.0 | 2023-09-27 09:32:53.539 | error | Growatt exception: Error: {"result":-1}
growatt.0 | 2023-09-27 09:02:49.396 | warn | Login:{}
growatt.0 | 2023-09-27 09:00:45.263 | error | Growatt exception: AxiosError: Request failed with status code 500
growatt.0 | 2023-09-27 08:31:09.500 | error | Growatt exception: AxiosError: Request failed with status code 500
`

**Comment by passuff** [comment]
Got a new warning message that I want to share with you.

`

growatt.0 | 2023-09-27 12:11:41.618 | info | not connected
-- | -- | -- | --
growatt.0 | 2023-09-27 12:11:41.617 | warn | Login:{"message":"Request failed with status code 500","name":"AxiosError","stack":"AxiosError: Request failed with status code 500\n at settle (/opt/iobroker/node_modules/growatt/node_modules/axios/lib/core/settle.js:19:12)\n at IncomingMessage.handleStreamEnd (/opt/iobroker/node_modules/growatt/node_modules/axios/lib/adapters/http.js:572:11)\n at IncomingMessage.emit (node:events:526:35)\n at IncomingMessage.emit (node:domain:489:12)\n at endReadableNT (node:internal/streams/readable:1359:12)\n at processTicksAndRejections (node:internal/process/task_queues:82:21)","config":{"transitional":{"silentJSONParsing":true,"forcedJSONParsing":true,"clarifyTimeoutError":false},"adapter":"http","transformRequest":[null],"transformResponse":[null],"timeout":60000,"xsrfCookieName":"XSRF-TOKEN","xsrfHeaderName":"X-XSRF-TOKEN","maxContentLength":-1,"maxBodyLength":-1,"env":{},"headers":{"Accept":"application/json, text/plain, */*","Content-Type":"application/x-www-form-urlencoded","User-Agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.0.0 Safari/537.36","Connection":"keep-alive","Content-Length":"48","Accept-Encoding":"gzip, compress, deflate, br"},"baseURL":"https://server.growatt.com","httpsAgent":{"_events":{},"_eventsCount":2,"_maxListeners":100,"defaultPort":443,"protocol":"https:","options":{"rejectUnauthorized":false,"noDelay":true,"path":null},"requests":{},"sockets":{"server.growatt.com:443::::::::false:::::::::::::":[{"_tlsOptions":{"pipe":false,"secureContext":{"context":{}},"isServer":false,"requestCert":true,"rejectUnauthorized":false},"_secureEstablished":true,"_securePending":false,"_newSessionPending":false,"_controlReleased":true,"secureConnecting":false,"_SNICallback":null,"servername":"server.growatt.com","alpnProtocol":false,"authorized":true,"authorizationError":null,"encrypted":true,"_events":{"close":[null,null,null],"timeout":[null,null]},"_eventsCount":8,"connecting":false,"_hadError":false,"_parent":null,"_host":"server.growatt.com","_closeAfterHandlingError":false,"_readableState":{"objectMode":false,"highWaterMark":16384,"buffer":{"head":null,"tail":null,"length":0},"length":0,"pipes":[],"flowing":true,"ended":false,"endEmitted":false,"reading":true,"constructed":true,"sync":false,"needReadable":true,"emittedReadable":false,"readableListening":false,"resumeScheduled":false,"errorEmitted":false,"emitClose":false,"autoDestroy":true,"destroyed":true,"errored":null,"closed":true,"closeEmitted":true,"defaultEncoding":"utf8","awaitDrainWriters":null,"multiAwaitDrain":false,"readingMore":false,"dataEmitted":true,"decoder":null,"encoding":null},"_maxListeners":100,"_writableState":{"objectMode":false,"highWaterMark":16384,"finalCalled":false,"needDrain":false,"ending":false,"ended":false,"finished":false,"destroyed":true,"decodeStrings":false,"defaultEncoding":"utf8","length":0,"writing":false,"corked":0,"sync":false,"bufferProcessing":false,"writecb":null,"writelen":0,"afterWriteTickInfo":null,"buffered":[],"bufferedIndex":0,"allBuffers":true,"allNoop":true,"pendingcb":0,"constructed":true,"prefinished":false,"errorEmitted":false,"emitClose":false,"autoDestroy":true,"errored":null,"closed":true,"closeEmitted":true},"allowHalfOpen":false,"_sockname":null,"_pendingData":null,"_pendingEncoding":"","_server":null,"ssl":null,"_requestCert":true,"_rejectUnauthorized":false,"parser":null,"_httpMessage":{"_events":{"error":[null,null]},"_eventsCount":7,"_maxListeners":100,"outputData":[],"outputSize":0,"writable":true,"destroyed":true,"_last":true,"chunkedEncoding":false,"shouldKeepAlive":true,"maxRequestsOnConnectionReached":false,"_defaultKeepAlive":true,"useChunkedEncodingByDefault":true,"sendDate":false,"_removedConnection":false,"_removedContLen":false,"_removedTE":false,"strictContentLength":false,"_contentLength":"48","_hasBody":true,"_trailer":"","finished":true,"_headerSent":true,"_closed":true,"_header":"POST /login HTTP/1.1\r\nAccept: application/json, text/plain, */*\r\nContent-Type: application/x-www-form-urlencoded\r\nUser-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.0.0 Safari/537.36\r\nConnection: keep-alive\r\nContent-Length: 48\r\nAccept-Encoding: gzip, compress, deflate, br\r\nsentry-trace: 68b122e991804daf8907058af7f8c783-afcc24e20c4e1a5a\r\nbaggage: sentry-environment=production,sentry-release=iobroker.growatt%403.2.1,sentry-public_key=580e0de8b3414b6caba783785eb4e240,sentry-trace_id=68b122e991804daf8907058af7f8c783\r\nHost: server.growatt.com\r\n\r\n","_keepAliveTimeout":0,"method":"POST","path":"/login","_ended":true,"res":{"_readableState":{"objectMode":false,"highWaterMark":16384,"buffer":{"head":null,"tail":null,"length":0},"length":0,"pipes":[],"flowing":true,"ended":true,"endEmitted":true,"reading":false,"constructed":true,"sync":true,"needReadable":false,"emittedReadable":false,"readableListening":false,"resumeScheduled":false,"errorEmitted":false,"emitClose":true,"autoDestroy":true,"destroyed":true,"errored":null,"closed":true,"closeEmitted":true,"defaultEncoding":"utf8","awaitDrainWriters":null,"multiAwaitDrain":false,"readingMore":true,"dataEmitted":true,"decoder":null,"encoding":null},"_events":{"end":[null,null]},"_eventsCount":4,"_maxListeners":100,"socket":null,"httpVersionMajor":1,"httpVersionMinor":1,"httpVersion":"1.1","complete":true,"rawHeaders":["Date","Wed, 27 Sep 2023 10:11:41 GMT","Content-Type","text/html;charset=UTF-8","Content-Length","445","Connection","keep-alive","Set-Cookie","JSESSIONID=FDE10EFB4FC54CB6245BB32958EB93A3; Path=/; Secure; HttpOnly","Set-Cookie","mapLang=com; Expires=Fri, 27-Oct-2023 10:11:37 GMT; Path=/"],"rawTrailers":[],"aborted":false,"upgrade":false,"url":"","method":null,"statusCode":500,"statusMessage":"Internal Server Error","_consuming":false,"_dumped":false,"responseUrl":"https://server.growatt.com/login","redirects":[]},"aborted":false,"timeoutCb":null,"upgradeOrConnect":false,"parser":null,"maxHeadersCount":null,"reusedSocket":false,"host":"server.growatt.com","protocol":"https:","_redirectable":{"_writableState":{"objectMode":false,"highWaterMark":16384,"finalCalled":false,"needDrain":false,"ending":false,"ended":false,"finished":false,"destroyed":false,"decodeStrings":true,"defaultEncoding":"utf8","length":0,"writing":false,"corked":0,"sync":true,"bufferProcessing":false,"writecb":null,"writelen":0,"afterWriteTickInfo":null,"buffered":[],"bufferedIndex":0,"allBuffers":true,"allNoop":true,"pendingcb":0,"constructed":true,"prefinished":false,"errorEmitted":false,"emitClose":true,"autoDestroy":true,"errored":null,"closed":false,"closeEmitted":false},"_events":{"socket":[null,null]},"_eventsCount":3,"_maxListeners":100,"_options":{"maxRedirects":21,"maxBodyLength":null,"protocol":"https:","path":"/login","method":"POST","headers":{"Accept":"application/json, text/plain, */*","Content-Type":"application/x-www-form-urlencoded","User-Agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.0.0 Safari/537.36","Connection":"keep-alive","Content-Length":"48","Accept-Encoding":"gzip, compress, deflate, br","sentry-trace":"68b122e991804daf8907058af7f8c783-afcc24e20c4e1a5a","baggage":"sentry-environment=production,sentry-release=iobroker.growatt%403.2.1,sentry-public_key=580e0de8b3414b6caba783785eb4e240,sentry-trace_id=68b122e991804daf8907058af7f8c783"},"agents":{},"beforeRedirects":{},"hostname":"server.growatt.com","port":"","nativeProtocols":{"http:":{"METHODS":["ACL","BIND","CHECKOUT","CONNECT","COPY","DELETE","GET","HEAD","LINK","LOCK","M-SEARCH","MERGE","MKACTIVITY","MKCALENDAR","MKCOL","MOVE","NOTIFY","OPTIONS","PATCH","POST","PROPFIND","PROPPATCH","PURGE","PUT","REBIND","REPORT","SEARCH","SOURCE","SUBSCRIBE","TRACE","UNBIND","UNLINK","UNLOCK","UNSUBSCRIBE"],"STATUS_CODES":{"100":"Continue","101":"Switching Protocols","102":"Processing","103":"Early Hints","200":"OK","201":"Created","202":"Accepted","203":"Non-Authoritative Information","204":"No Content","205":"Reset Content","206":"Partial Content","207":"Multi-Status","208":"Already Reported","226":"IM Used","300":"Multiple Choices","301":"Moved Permanently","302":"Found","303":"See Other","304":"Not Modified","305":"Use Proxy","307":"Temporary Redirect","308":"Permanent Redirect","400":"Bad Request","401":"Unauthorized","402":"Payment Required","403":"Forbidden","404":"Not Found","405":"Method Not Allowed","406":"Not Acceptable","407":"Proxy Authentication Required","408":"Request Timeout","409":"Conflict","410":"Gone","411":"Length Required","412":"Precondition Failed","413":"Payload Too Large","414":"URI Too Long","415":"Unsupported Media Type","416":"Range Not Satisfiable","417":"Expectation Failed","418":"I'm a Teapot","421":"Misdirected Request","422":"Unprocessable Entity","423":"Locked","424":"Failed Dependency","425":"Too Early","426":"Upgrade Required","428":"Precondition Required","429":"Too Many Requests","431":"Request Header Fields Too Large","451":"Unavailable For Legal Reasons","500":"Internal Server Error","501":"Not Implemented","502":"Bad Gateway","503":"Service Unavailable","504":"Gateway Timeout","505":"HTTP Version Not Supported","506":"Variant Also Negotiates","507":"Insufficient Storage","508":"Loop Detected","509":"Bandwidth Limit Exceeded","510":"Not Extended","511":"Network Authentication Required"},"maxHeaderSize":16384,"globalAgent":{"_events":{},"_eventsCount":2,"defaultPort":80,"protocol":"http:","options":{"noDelay":true,"path":null},"requests":{},"sockets":{},"freeSockets":{},"keepAliveMsecs":1000,"keepAlive":false,"maxSockets":null,"maxFreeSockets":256,"scheduling":"lifo","maxTotalSockets":null,"totalSocketCount":0}},"https:":{"globalAgent":{"_events":{},"_eventsCount":2,"defaultPort":443,"protocol":"https:","options":{"noDelay":true,"path":null},"requests":{},"sockets":{},"freeSockets":{},"keepAliveMsecs":1000,"keepAlive":false,"maxSockets":null,"maxFreeSockets":256,"scheduling":"lifo","maxTotalSockets":null,"totalSocketCount":0,"maxCachedSessions":100,"_sessionCache":{"map":{},"list":[]}}}},"pathname":"/login"},"_ended":true,"_ending":true,"_redirectCount":0,"_redirects":[],"_requestBodyLength":48,"_requestBodyBuffers":[],"_currentUrl":"https://server.growatt.com/login","_timeout":null}},"timeout":60000}]},"freeSockets":{},"keepAliveMsecs":1000,"keepAlive":false,"maxSockets":null,"maxFreeSockets":256,"scheduling":"lifo","maxTotalSockets":null,"totalSocketCount":1,"maxCachedSessions":100,"_sessionCache":{"map":{"server.growatt.com:443::::::::false:::::::::::::":{"type":"Buffer","data":[48,130,7,111,2,1,1,2,2,3,3,4,2,192,47,4,32,249,32,3,70,16,131,245,65,143,89,69,95,182,131,245,82,87,41,128,56,73,126,34,194,168,8,227,37,126,251,181,96,4,48,161,253,65,217,163,214,60,206,152,139,212,5,206,9,221,48,205,126,112,245,52,51,193,7,89,79,239,251,155,235,110,96,215,102,225,121,245,238,13,233,127,172,112,128,100,221,251,110,161,6,2,4,101,19,255,217,162,4,2,2,28,32,163,130,5,254,48,130,5,250,48,130,4,226,160,3,2,1,2,2,16,9,85,12,68,232,19,121,140,55,58,209,168,74,191,224,9,48,13,6,9,42,134,72,134,247,13,1,1,11,5,0,48,110,49,11,48,9,6,3,85,4,6,19,2,85,83,49,21,48,19,6,3,85,4,10,19,12,68,105,103,105,67,101,114,116,32,73,110,99,49,25,48,23,6,3,85,4,11,19,16,119,119,119,46,100,105,103,105,99,101,114,116,46,99,111,109,49,45,48,43,6,3,85,4,3,19,36,69,110,99,114,121,112,116,105,111,110,32,69,118,101,114,121,119,104,101,114,101,32,68,86,32,84,76,83,32,67,65,32,45,32,71,49,48,30,23,13,50,51,48,51,48,53,48,48,48,48,48,48,90,23,13,50,52,48,51,48,53,50,51,53,57,53,57,90,48,29,49,27,48,25,6,3,85,4,3,19,18,115,101,114,118,101,114,46,103,114,111,119,97,116,116,46,99,111,109,48,130,1,34,48,13,6,9,42,134,72,134,247,13,1,1,1,5,0,3,130,1,15,0,48,130,1,10,2,130,1,1,0,164,243,240,8,180,63,250,0,193,122,86,185,221,88,119,240,125,32,149,155,5,74,22,14,158,110,17,235,176,76,184,254,144,109,117,52,17,133,178,170,33,2,248,142,44,188,183,13,138,68,237,203,97,119,205,123,81,40,154,51,51,251,213,187,4,126,195,120,39,248,179,51,70,36,251,112,161,15,73,25,138,16,227,93,143,244,34,122,47,140,27,153,179,7,154,116,147,168,175,81,75,42,188,15,254,0,208,127,133,126,97,45,238,250,41,50,201,2,198,165,248,174,37,42,21,230,187,228,67,200,22,255,236,50,138,10,100,141,66,145,47,11,97,74,80,101,100,11,194,244,238,90,129,199,50,212,171,59,80,230,16,188,105,206,174,211,147,21,122,71,6,196,139,100,126,81,150,246,221,75,112,49,52,129,100,236,7,233,248,5,159,82,195,240,218,5,116,3,248,216,186,71,238,145,221,185,9,251,223,219,5,80,170,204,127,199,230,73,30,233,98,57,108,96,63,200,164,171,124,13,198,13,170,212,222,226,177,76,179,228,135,30,225,34,103,156,3,98,43,102,43,193,77,223,98,79,2,3,1,0,1,163,130,2,227,48,130,2,223,48,31,6,3,85,29,35,4,24,48,22,128,20,85,116,79,178,114,79,245,96,186,80,209,215,230,81,92,154,1,135,26,215,48,29,6,3,85,29,14,4,22,4,20,204,41,195,87,171,103,162,140,8,227,64,148,126,170,79,158,104,165,87,174,48,29,6,3,85,29,17,4,22,48,20,130,18,115,101,114,118,101,114,46,103,114,111,119,97,116,116,46,99,111,109,48,14,6,3,85,29,15,1,1,255,4,4,3,2,5,160,48,29,6,3,85,29,37,4,22,48,20,6,8,43,6,1,5,5,7,3,1,6,8,43,6,1,5,5,7,3,2,48,62,6,3,85,29,32,4,55,48,53,48,51,6,6,103,129,12,1,2,1,48,41,48,39,6,8,43,6,1,5,5,7,2,1,22,27,104,116,116,112,58,47,47,119,119,119,46,100,105,103,105,99,101,114,116,46,99,111,109,47,67,80,83,48,129,128,6,8,43,6,1,5,5,7,1,1,4,116,48,114,48,36,6,8,43,6,1,5,5,7,48,1,134,24,104,116,116,112,58,47,47,111,99,115,112,46,100,105,103,105,99,101,114,116,46,99,111,109,48,74,6,8,43,6,1,5,5,7,48,2,134,62,104,116,116,112,58,47,47,99,97,99,101,114,116,115,46,100,105,103,105,99,101,114,116,46,99,111,109,47,69,110,99,114,121,112,116,105,111,110,69,118,101,114,121,119,104,101,114,101,68,86,84,76,83,67,65,45,71,49,46,99,114,116,48,9,6,3,85,29,19,4,2,48,0,48,130,1,127,6,10,43,6,1,4,1,214,121,2,4,2,4,130,1,111,4,130,1,107,1,105,0,118,0,238,205,208,100,213,219,26,206,197,92,183,157,180,205,19,162,50,135,70,124,188,236,222,195,81,72,89,70,113,31,181,155,0,0,1,134,175,87,17,68,0,0,4,3,0,71,48,69,2,32,117,57,147,234,173,223,51,76,196,23,146,118,141,223,36,100,105,253,126,230,53,199,94,23,186,169,137,106,184,147,28,130,2,33,0,138,230,7,68,132,134,78,170,65,122,85,221,91,125,84,209,180,198,235,187,143,235,17,127,86,30,131,44,212,135,162,191,0,119,0,115,217,158,137,27,76,150,120,160,32,125,71,157,230,178,198,28,208,81,94,113,25,42,140,107,128,16,122,193,119,114,181,0,0,1,134,175,87,17,131,0,0,4,3,0,72,48,70,2,33,0,205,96,194,144,235,80,197,157,1,142,216,169,128,174,138,160,183,101,136,74,231,9,199,81,236,142,163,175,27,8,153,112,2,33,0,151,26,248,189,66,172,68,247,39,154,108,239,244,112,67,20,28,255,126,34,27,190,232,100,101,225,153,99,110,45,2,147,0,118,0,72,176,227,107,218,166,71,52,15,229,106,2,250,157,48,235,28,82,1,203,86,221,44,129,217,187,191,171,57,216,132,115,0,0,1,134,175,87,17,82,0,0,4,3,0,71,48,69,2,32,77,154,108,198,74,191,209,157,236,33,93,38,89,233,226,183,191,123,147,63,252,95,90,169,182,9,59,78,163,239,105,128,2,33,0,187,151,210,155,93,164,43,34,214,169,236,88,245,43,73,52,19,185,208,89,25,166,166,74,241,163,158,115,219,192,66,202,48,13,6,9,42,134,72,134,247,13,1,1,11,5,0,3,130,1,1,0,67,103,15,65,229,42,120,108,202,3,84,46,40,51,119,136,81,110,209,65,175,124,21,220,41,205,10,159,209,52,27,68,161,142,133,148,44,49,157,221,54,16,29,237,120,168,140,60,146,201,72,50,163,197,201,39,246,5,53,228,76,196,135,34,139,180,5,146,44,243,61,36,38,39,31,58,164,245,1,27,176,73,191,0,2,202,19,251,241,145,28,209,161,97,80,141,156,21,113,204,68,255,227,26,84,187,84,34,219,42,225,236,44,55,120,105,101,32,213,66,10,125,132,84,205,85,96,116,231,111,254,6,194,243,127,10,248,220,150,202,181,133,248,170,211,145,122,106,213,206,56,39,205,227,0,120,223,165,221,127,118,81,57,127,205,177,159,21,205,254,28,20,200,192,175,83,59,123,144,203,71,36,91,88,170,72,194,109,60,33,241,219,25,165,95,203,153,150,224,25,14,193,59,130,199,63,4,190,18,222,140,241,218,25,249,137,172,226,36,174,74,15,141,193,124,168,96,172,13,238,181,163,162,23,247,119,41,59,212,44,72,95,137,135,29,223,213,47,10,172,66,221,106,232,205,137,164,2,4,0,166,20,4,18,115,101,114,118,101,114,46,103,114,111,119,97,116,116,46,99,111,109,169,4,2,2,1,44,170,129,211,4,129,208,74,105,57,108,68,89,88,76,122,105,73,113,119,99,89,122,242,200,100,79,124,191,156,119,172,199,234,155,81,245,227,242,236,172,47,64,144,149,179,179,188,176,167,24,191,204,36,245,20,168,128,161,114,230,51,217,226,60,65,195,47,162,150,16,204,145,102,236,17,169,149,99,217,83,236,166,183,170,252,87,189,148,67,201,125,13,242,73,184,25,7,108,45,166,48,217,23,174,90,230,136,138,26,227,92,135,173,182,4,238,238,105,221,220,83,231,36,48,166,102,27,83,48,163,147,129,6,230,248,77,52,75,90,67,141,209,76,224,61,118,215,136,6,149,49,135,93,189,42,232,189,21,61,113,93,135,182,199,248,23,98,198,199,224,95,177,6,79,123,85,109,179,244,33,9,120,245,2,32,68,207,71,249,251,97,161,9,244,202,25,25,218,84,240,88,228,70,34,40,2,194,123,140,241,224,179,114,190,173,3,2,1,1,179,3,2,1,29]}},"list":["server.growatt.com:443::::::::false:::::::::::::"]}},"method":"post","url":"https://server.growatt.com/login","data":"account=passuff&password=fuckyou84&validateCode="},"code":"ERR_BAD_RESPONSE","status":500}
growatt.0 | 2023-09-27 12:09:36.987 | error | Growatt exception: AxiosError: Request failed with status code 500
growatt.0 | 2023-09-27 12:07:26.387 | info | not connected
growatt.0 | 2023-09-27 12:07:26.386 | warn | Login:{}
growatt.0 | 2023-09-27 12:05:22.315 | error | Growatt exception: Error: The server sent an unexpected response, a fatal error has occurred
growatt.0 | 2023-09-27 12:03:16.757 | error | Growatt exception: Error: {"result":-1}

`

**Comment by PLCHome** [comment]
![image](https://github.com/PLCHome/ioBroker.growatt/assets/29116097/8160eddf-6df1-400c-a5fe-5b5c6869d4e3)

There are probably cloud problems at the moment. The app doesn't work properly either. Unfortunately I have no influence on the website.

**Comment by PLCHome** [comment]
![image](https://github.com/PLCHome/ioBroker.growatt/assets/29116097/59ad1601-7170-47fd-86ac-0beb79f7e7f7)

**Comment by PLCHome** [comment]
Please contact Growatt
