### ISSUE TITLE
No connection sinsce last night - nothing changed

### ISSUE THREAD

**Issue by tziegenbein** [PLCHome/ioBroker.growatt#40]
i am using the adapter growat 3.2.3
last night the connection was lost. No objects are available. 

no connection to device or service.

i changed nothing and rewrite credentials. With these credentials i can open growatt dashboard on the homepage from growatt. There are all data from shine adapter. But no data in the adapter in iobroker. 

Node.js: v18.17.1
NPM: 10.2.2

Thanks for help

**Comment by Transalpler** [comment]
I have the same Issue - thats whats written to the Log:
<html>
<body>

growatt.0 | 334124 | 2024-07-03 13:07:51.587 | warn | Growatt login: Error: The server sent an unexpected response: /error.do?errorMess=errorNoLogin
-- | -- | -- | -- | --
growatt.0 | 334124 | 2024-07-03 13:07:50.656 | info | Growatt relogin on session failed: Error: The server sent an unexpected response: /error.do?errorMess=errorNoLogin
growatt.0 | 334124 | 2024-07-03 13:07:49.940 | info | starting. Version 3.2.3 in /opt/iobroker/node_modules/iobroker.growatt, node: v18.20.0, js-controller: 5.0.19


</body>
</html>

**Comment by Tingeltangelbobi** [comment]
I have the same Issue

**Comment by treck** [comment]
Same issue here

**Comment by Crusher606** [comment]
I have the same issue.
v3.2.3

**Comment by PLCHome** [comment]
fixed v3.2.4

**Comment by treck** [comment]
Thanks for the quick response!

**Comment by Tingeltangelbobi** [comment]
thanks it works again
