### ISSUE TITLE
Growatt 3.2.3: Fehler beim Login

### ISSUE THREAD

**Issue by HJS72** [PLCHome/ioBroker.growatt#43]
Hallo,
Nach einigen Tagen ohne Probleme kann sich der Adapter nicht mehr am Backend anmelden.
"warn	Login:{}"

Username/Passwort mehrfach geprüft - Anmeldung bei https://server.growatt.com/ geht problemlos.
Hat sonst noch jemand das Problem?

Gruß Stefan

**Comment by PLCHome** [comment]
fixed v3.2.4
https://github.com/PLCHome/ioBroker.growatt/issues/40
The version has been in beta repro since Wednesday. Testing is underway to move it to stable. Normally it takes 4 weeks.
