### ISSUE TITLE
any chance to set time slots for load prios?

### ISSUE THREAD

**Issue by olli0815** [PLCHome/ioBroker.growatt#51]
No bug, rather an ask - but 
fist things first Thanks for the Adapter !!.

Would it be possible to set more values then the given channels under settings?
background I wand to set load prios more dynamic to reflect dynamic energy tariffs.

![Bildschirmfoto vom 2024-09-16 18-04-05](https://github.com/user-attachments/assets/da6c7862-22df-4c6b-abc2-4e6bdbbe6e6c)
Ole

**Comment by PLCHome** [comment]
For MIX this is implemented. What type is this?

**Comment by PLCHome** [comment]
Oh sorry, the type of the used interface by the webgui out of this datapoint: 
growatt.<nr>.<nr>.devices.<sn>.growattType

**Comment by olli0815** [comment]
tlxh

**Comment by PLCHome** [comment]
Ok that make sense. If you activate the "advanced settings" is there a possibility to read the time slots?

**Comment by olli0815** [comment]
No, Not yet.
I ticket all options, no time slots in the data.

**Comment by PLCHome** [comment]
Just writing can also work, but then it's a blind flight because it only works in one direction.
To explain: The values ​​are displayed when you open the page on the Growatt homepage. However, they are transmitted in the source code of the page. But that's not how the adapter works. It would like to query the values. If there is no way to query the values, I don't like to implement it.

**Comment by olli0815** [comment]
Makes sense.
How to check if they are readable?

**Comment by PLCHome** [comment]
On the mix I can read every parameter:
![image](https://github.com/user-attachments/assets/df0944b8-2b9a-46fc-9317-ec086bfe6b5b)

**Comment by olli0815** [comment]
![Bildschirmfoto vom 2024-10-04 15-22-51](https://github.com/user-attachments/assets/0164f356-928c-46d1-a48e-fdb36c4b7d6d)
I'm able to read the "slots" too via App / WebInterface

**Comment by olli0815** [comment]
enjoy !!

**Comment by PLCHome** [comment]
![image](https://github.com/user-attachments/assets/e9534dc1-2cab-45a3-b480-57f646064196)

`{"msg":"inv_set_success","success":true}`

![image](https://github.com/user-attachments/assets/a76cc37d-1f28-4ffe-ad3d-abb1cf0074aa)

**Comment by PLCHome** [comment]
`      gridFirst: {
        name: 'Grid first',
        type: 'mix_ac_discharge_time_period',
        paramId: 'MIX_AC_DISCHARGE_TIME_MULTI',
        parseRet: PARSERET.parseGritFirst,
        param: {
          param1: { name: 'Discharge power rate', type: 'INUM_0_100', unit: '%' },
          param2: { name: 'Discharge stopped soc', type: 'INUM_0_100', unit: '%' },
          param3: { name: 'Time slot 1 start HH', type: 'INUM_0_24' },
          param4: { name: 'Time slot 1 start MI', type: 'INUM_0_60' },
          param5: { name: 'Time slot 1 end HH', type: 'INUM_0_24' },
          param6: { name: 'Time slot 1 end MI', type: 'INUM_0_60' },
          param7: { name: 'Time slot 1 on', type: 'BOOL' },
          param8: { name: 'Time slot 2 start HH', type: 'INUM_0_24' },
          param9: { name: 'Time slot 2 start MI', type: 'INUM_0_60' },
          param10: { name: 'Time slot 2 end HH', type: 'INUM_0_24' },
          param11: { name: 'Time slot 2 end MI', type: 'INUM_0_60' },
          param12: { name: 'Time slot 2 on', type: 'BOOL' },
          param13: { name: 'Time slot 3 start HH', type: 'INUM_0_24' },
          param14: { name: 'Time slot 3 start MI', type: 'INUM_0_60' },
          param15: { name: 'Time slot 3 end HH', type: 'INUM_0_24' },
          param16: { name: 'Time slot 3 end MI', type: 'INUM_0_60' },
          param17: { name: 'Time Slot 3 on', type: 'BOOL' },
        },`
And that is then incorporated into the source code... actually no secret

**Comment by olli0815** [comment]
do you plan to implement?

**Comment by PLCHome** [comment]
You would have to provide the information as described above, then I will include it and give you advice on how to test it

**Comment by olli0815** [comment]
![Bildschirmfoto vom 2024-10-23 14-11-42](https://github.com/user-attachments/assets/9926814d-eed7-422e-a8b8-8f8512ad05de)

**Comment by olli0815** [comment]
![Bildschirmfoto vom 2024-10-23 14-11-42](https://github.com/user-attachments/assets/38959e4e-6761-4d5a-91a1-b352f12638be)

**Comment by olli0815** [comment]
let me know if there is more info required

**Comment by PLCHome** [comment]
Can you give me the response json from both?
Is it time_segment1, time_segment2 .. time_segment9 for all?

**Comment by olli0815** [comment]
> Can you give me the response json from both? 
Is it time_segment1, time_segment2 .. time_segment9 for all? yes

**Comment by olli0815** [comment]
->	
action	"tlxSet"
serialNum	"CZM0CMK04A"
type	"time_segment1"
param1	"1"
param2	"14"
param3	"00"
param4	"16"
param5	"00"
param6	"0"
<-
msg	"inv_set_success"
success	true

**Comment by PLCHome** [comment]
one tab further, as should be JSON as text in brackets {}

**Comment by olli0815** [comment]
in firefox?
{"msg":"inv_set_success","success":true}
??

**Comment by PLCHome** [comment]
> in firefox?
> {"msg":"inv_set_success","success":true}
> ??
Yes

But it is more complicated than it seems at first glance.

Let's start with sending.
param1 "1" and param6 "0" in the picture in the first message you can see "Battery First", "Load First". Please go through them all once and make a list of which selection is which number. 

It is also important whether it is param1 or param6 . 

The other will probably be Eanabel / Daisabel. Probably 0 Disable / 1 Eanabel but please check that too.

**Comment by olli0815** [comment]
action	"tlxSet"
serialNum	"ChhhA"
type	"time_segment1"
param1	"1" = Load First "2" = Battery First" "3" = Grid First
param2	"14" = hh_start
param3	"00" = mm_start
param4	"16" = hh_end
param5	"00" = mm_end
param6	"0"  = Disable "1" = Enable

**Comment by PLCHome** [comment]
Great thats easy! 
Now the answer of readMinParam: {"msg":"11776-4096-","success":true}
This will not be so easy
Here you should try Param 1 with the same Param 2 to 6. Then Param 6. Then make a few changes to Param 2 to 5 with Param 1 and Param 6 fixed.
We'll guess, but I need a few samples.

I think 4096 is 1000 in HEX
that gives the low byte 00 in decimal which is 0 minutes
And the high byte 10 in decimal which is 16 hours
So the up time

But 11776 is 2E00 in HEX
that gives the low byte still 00 in decimal which is 0 minutes
And the high byte 2E in decimal which is 46 hours, which is nonsense.
But you only need 5 bits to represent 24:
2E is therefore 0010 1110 if we delete the first 3 bits this gives 0000 1110 or 0E which corresponds to 14 hours.


I now suspect that the query will return the following result:

I'm guessing please check it now

param1 "1" = Load First
param2 "14" = hh_start
param3 "30" = mm_start
results in $2E1E so 11806

param1 "2" = Battery First"
param2 "14" = hh_start
param3 "30" = mm_start
results in $4E1E so 19998

param1 "3" = Grid First
param2 "14" = hh_start
param3 "30" = mm_start
results in $6E1E so 28190

For the first number between "-"

param4 "16" = hh_end
param5 "30" = mm_end
param6 "0" = Disable
results in $101E so ‭4126‬

param4 "16" = hh_end
param5 "30" = mm_end
param6 "1" = Enable
results in $201E so ‭8222‬

For the second number. But here you can be completely wrong

**Comment by olli0815** [comment]
I ask a diggi buddy:

Thank you for providing another test case. Here's the updated configuration for Time Slot 1:

    Mode: 0
    Start Time: 18:00
    End Time: 19:30
    Enable: 0
    Message: "4608-4894-"

Key Observations:

    Start Address:
        The start address remains the same as in the previous case where Enable = 0 and the Start Time was 18:00 (4608).
    End Address:
        The end address has changed from 4638 (in the previous case with 18:00 to 18:30 end time) to 4894 with the updated end time of 19:30.
        This change indicates that the End Time directly affects the end address.

Hypothesis:

    Start Address (4608): This confirms that when Enable = 0, the system uses a lower memory block (starting around 4600), regardless of the End Time.

    End Address Shift:
        In the previous test cases:
            With End Time = 18:30, the end address was 4638.
            With End Time = 19:30, the end address has increased to 4894.
        The difference in the end address (4894 - 4638 = 256) suggests that the End Time causes the end address to shift in 256-unit increments per hour.

Pattern Summary:

    Enable Flag:
        When Enable = 0, the start address stays in the lower memory range (4608 in this case).
        When Enable = 1, the system seems to use a higher memory range (e.g., 37376).

    Start Time:
        The Start Time (18:00) doesn't affect the start address in this case since it remains fixed at 4608 when Enable = 0.

    End Time:
        The End Time has a clear impact on the end address, with the address increasing by 256 units per hour.
        For 18:30, the end address is 4638.
        For 19:30, the end address is 4894.

Prediction Based on Pattern:

    If we change the End Time to another hour, we can expect the end address to shift in increments of 256 units. For example, if the End Time were set to 20:30, the end address would likely increase by another 256 units, resulting in 5150.

Conclusion:

    The Enable flag plays a significant role in determining the memory block range, while the End Time directly affects the end address in predictable increments.

If you have more cases or want to explore different settings, feel free to provide additional test cases!

**Comment by olli0815** [comment]
sound complicated but gpt gets the correct results to predict the response message

**Comment by PLCHome** [comment]
Please give me the 5 results from the reading after setting these parameters:

param1 "1" = Load First
param2 "14" = hh_start
param3 "30" = mm_start
param4 "16"
param5 "00"
param6 "0"

param1 "2" = Battery First"
param2 "14" = hh_start
param3 "30" = mm_start
param4 "16"
param5 "00"
param6 "0"

param1 "3" = Grid First
param2 "14" = hh_start
param3 "30" = mm_start
param4 "16"
param5 "00"
param6 "0"


param1 "1" = Load First
param2 "14" = hh_start
param3 "00" = mm_start
param4 "16" = hh_end
param5 "30" = mm_end
param6 "0" = Disable

param1 "1" = Load First
param2 "14" = hh_start
param3 "00" = mm_start
param4 "16" = hh_end
param5 "30" = mm_end
param6 "1" = Enable

thats all, thanx

**Comment by olli0815** [comment]
give me a sec

**Comment by olli0815** [comment]
Current Value(Time Slot 1)：Mode :0 Start Time:14:30 End Time:16:0 Enable:0 -> msg "3614-4096-"
Current Value(Time Slot 1)：Mode :1 Start Time:14:30 End Time:16:0 Enable:0 -> msg "11806-4096-"
Current Value(Time Slot 1)：Mode :2 Start Time:14:30 End Time:16:0 Enable:0 -> msg 19998-4096-
Current Value(Time Slot 1)：Mode :0 Start Time:14:0 End Time:16:30 Enable:0 -> msg 3584-4126-
Current Value(Time Slot 1)：Mode :0 Start Time:14:0 End Time:16:30 Enable:1 -> msg 36352-4126-

**Comment by olli0815** [comment]
Thank you for providing these additional test cases. They provide valuable insights into how Mode, Start Time, End Time, and Enable affect the memory message generation. Let's analyze and summarize the updated observations.
Test Case Summary:

    Mode: 0, Start Time: 14:30, End Time: 16:00, Enable: 0
        Message: "3614-4096-"

    Mode: 1, Start Time: 14:30, End Time: 16:00, Enable: 0
        Message: "11806-4096-"

    Mode: 2, Start Time: 14:30, End Time: 16:00, Enable: 0
        Message: "19998-4096-"

    Mode: 0, Start Time: 14:00, End Time: 16:30, Enable: 0
        Message: "3584-4126-"

    Mode: 0, Start Time: 14:00, End Time: 16:30, Enable: 1
        Message: "36352-4126-"

Key Observations:
1. Effect of Mode:

    Mode significantly shifts the Start Address while the End Address remains unaffected.
    Mode 0 starts with lower addresses.
        Mode 0: 3614
        Mode 1: 11806 (approximately a shift of 8192 units compared to Mode 0).
        Mode 2: 19998 (again, approximately an 8192 unit increase over Mode 1).
    This suggests that each Mode adds around 8192 units to the base start address, indicating that different modes are allocated distinct memory regions.

2. Start Time Influence:

    Changing the Start Time results in small shifts in the Start Address.
        For 14:30, the Start Address is 3614.
        For 14:00, the Start Address drops to 3584.
        This confirms the earlier observation that each minute results in a small shift in the start address, likely around 1 unit per minute when Enable = 0.

3. End Time Influence:

    The End Address changes based on the End Time, with the same pattern:
        From 16:00 (address: 4096) to 16:30 (address: 4126), the End Address shifts by 30 units, consistent with the pattern of 1 unit per minute.

4. Effect of Enable:

    Enable plays a major role in shifting the Start Address to a different memory block.
        Enable = 0 results in lower memory regions.
        Enable = 1 shifts the Start Address dramatically (e.g., from 3584 to 36352), implying that Enable = 1 allocates a higher memory block for the time slot configuration.

Algorithm Summary:

    Start Address:
        Mode: Adds approximately 8192 units per mode increment.
        Start Time: Shifts the Start Address by around 1 unit per minute.
        Enable:
            Enable = 0: Uses lower memory blocks.
            Enable = 1: Shifts the start address significantly to a higher block (as seen with a large jump to 36352).

    End Address:
        End Time shifts the End Address by 1 unit per minute.
        Example: A change from 16:00 to 16:30 increases the end address by 30 units.

Example Prediction:

Let's predict the message for a new case:

    Mode: 1
    Start Time: 14:00
    End Time: 16:30
    Enable: 0

Based on the above analysis:

    Base Start Address for Mode 0 at 14:00: 3584
    Mode 1: Add 8192 units to the base address:
    3584 + 8192 = 11776.
    End Time 16:30 results in an End Address of 4126 (as seen in the previous test case).

Predicted Message:

arduino

msg    "11776-4126-"
success    true

This prediction is based on the patterns observed from the test cases.

**Comment by olli0815** [comment]
Final Thoughts from GPT ;-)

The pattern is consistent across test cases, with:

    Mode causing large shifts of 8192 units per mode.
    Start Time and End Time affecting the memory addresses with finer granularity (1 unit per minute, 256 units per hour).
    Enable shifting the start address to a higher block when set to 1.

**Comment by PLCHome** [comment]
Please no more chat GPT output. I can ask him myself. 

For development and testing I need the real return values.



I have a completely different problem with the output. Above you write mode 1, 2, 3 below 0, 1, 2 I need that exactly. 



Is parameter 1 now 0 or 1?

**Comment by olli0815** [comment]
Okay.
For set: param1 "1" = Load First "2" = Battery First" "3" = Grid First

**Comment by olli0815** [comment]
just verified, sorry.

from 0 to 2

**Comment by PLCHome** [comment]
> param1 "1" = Load First "2" = Battery First" "3" = Grid First
 is what?

**Comment by olli0815** [comment]
param1 "0" = Load First "1" = Battery First" "2" = Grid First

**Comment by PLCHome** [comment]
In the node_module of the IoBroker you will find the iobroker.growatt directory. 
There exsits iobroker.growatt/node_modules/growatt if not then you will find parallel to the iobroker.growatt directory the growatt directory.

Please replace the following three files in lib directory:

https://github.com/PLCHome/growatt/blob/master/lib/growatttype.js
https://github.com/PLCHome/growatt/blob/master/lib/parseret.js
https://github.com/PLCHome/growatt/blob/master/lib/parsein.js

restart adapter in ioB and test...

**Comment by olli0815** [comment]
Will test it as soon I'm back.
Looking forward!! Thanks

**Comment by PLCHome** [comment]
![image](https://github.com/user-attachments/assets/1eb6e415-61b4-44e8-a2c0-830695df4cc6)

I use this with the MIX to save the battery. The MIX always charges the battery after sunset when it is close to the minimum.

I switch the inverter off after sunset when it is close to the minimum and switch it on again before sunrise.

Should we implement that too? 

Then you would have to read it out as well.

**Comment by olli0815** [comment]
action	         "tlxSet"
serialNum	"CkkkkkkkkkkkK04A"
type	        "tlx_on_off"
param1	        "0001"

**Comment by olli0815** [comment]
{"msg":"inv_set_success","success":true}

**Comment by olli0815** [comment]
how long is the time frame to restart?

**Comment by PLCHome** [comment]
Nicht lange wenn er nicht zurückkommt hat was nicht geklappt dann mal ins Log schauen.

**Comment by PLCHome** [comment]
> action "tlxSet" serialNum "CkkkkkkkkkkkK04A" type "tlx_on_off" param1 "0001" -> on

ist auch drin...

**Comment by olli0815** [comment]
don't receive a message for the "time" data point as well

**Comment by PLCHome** [comment]
> time slots not so far, shall I grab the log? which one?

Yes

**Comment by olli0815** [comment]
tried to sorted out a bit

**Comment by olli0815** [comment]
growatt.0	2024-10-24 16:26:31.400	debug	Enter growattData, Param: sessionHold:true
growatt.0	2024-10-24 16:26:31.179	silly	States system redis pmessage system.adapter.growatt.0.logLevel/system.adapter.growatt.0.logLevel:{"val":"silly","ack":true,"ts":1729779991171,"q":0,"from":"system.adapter.growatt.0","lc":1729775482531}
growatt.0	2024-10-24 16:26:31.159	info	starting. Version 3.2.5 (non-npm: PLCHome/ioBroker.growatt) in /opt/iobroker/node_modules/iobroker.growatt, node: v20.17.0, js-controller: 6.0.11
growatt.0	2024-10-24 16:26:30.751	debug	Plugin sentry Initialize Plugin (enabled=true)
growatt.0	2024-10-24 14:25:58.250	info	terminating
growatt.0	2024-10-24 14:25:57.981	debug	Leave growattLogout :248ms
growatt.0	2024-10-24 14:25:57.749	warn	Terminated (UNCAUGHT_EXCEPTION): Without reason
growatt.0	2024-10-24 14:25:57.748	debug	Plugin sentry destroyed
growatt.0	2024-10-24 14:25:57.748	info	terminating
growatt.0	2024-10-24 14:25:57.734	debug	Enter lifeSignCallback 600000ms
growatt.0	2024-10-24 14:25:57.733	debug	Enter growattLogout
growatt.0	2024-10-24 14:25:57.647	error	Cannot read properties of null (reading 'val')
growatt.0	2024-10-24 14:25:57.647	error	TypeError: Cannot read properties of null (reading 'val') at /opt/iobroker/node_modules/iobroker.growatt/growattMain.js:306:31 at async Promise.all (index 0) at Growatt.writeSetting (/opt/iobroker/node_modules/iobroker.growatt/growattMain.js:310:7)
growatt.0	2024-10-24 14:25:57.644	error	unhandled promise rejection: Cannot read properties of null (reading 'val')
growatt.0	2024-10-24 14:25:57.644	error	Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
growatt.0	2024-10-24 14:25:57.436	silly	States user redis pmessage growatt.0.*.write/growatt.0.1929535.devices.CZM0CMK04A.settings.timeSlot1.write:{"val":true,"ack":false,"ts":1729779957289,"q":0,"from":"system.adapter.admin.0","user":"system.user.admin","lc":1729779957289}
growatt.0	2024-10-24 14:25:54.946	debug	Growatt time for parseData : 58ms

**Comment by PLCHome** [comment]
INUM_0_2 is a new type... shit

**Comment by PLCHome** [comment]
please update this file in the iobroker.growatt directory

https://github.com/PLCHome/ioBroker.growatt/blob/master/growattMain.js

**Comment by olli0815** [comment]
nope, let me provide log.

**Comment by PLCHome** [comment]
Then you may have to delete the timeslots 1 to 9 and restart the adapter so that it creates them correctly

**Comment by olli0815** [comment]
[log.log](https://github.com/user-attachments/files/17509078/log.log)

**Comment by olli0815** [comment]
![Bildschirmfoto vom 2024-10-24 17-20-08](https://github.com/user-attachments/assets/a4603397-e966-4bfb-8868-fdf648030c29)

**Comment by PLCHome** [comment]
Can you enter correct values? This means that the value in Param1 is not present. It asks for the param and there is no value in the response.

The reading sockets give a valid response to timeSlot1: {"msg":"0-4126-","success":false} indicates success false.

**Comment by olli0815** [comment]
![image](https://github.com/user-attachments/assets/468b49e1-69e0-47f5-af4e-33516aa265d1)

**Comment by olli0815** [comment]
and posted - will check min

**Comment by olli0815** [comment]
![image](https://github.com/user-attachments/assets/71528147-69b8-4f9e-a3ba-51e906de6b4c)

**Comment by olli0815** [comment]
initial 0 or 00 doensn't work
values from 1 do

**Comment by olli0815** [comment]
BINGO !!

![image](https://github.com/user-attachments/assets/f6983a77-e5fe-438c-aa1c-7c71c695fb20)

**Comment by PLCHome** [comment]
> initial 0 or 00 doensn't work
> values from 1 do
I don't understand right now

**Comment by olli0815** [comment]
when trying to write the min I need to give numbers other then 0. 00 doesn't be interpreted from admin GUI, jumps back to 0.
when I use value > 1 11 for instance it works

**Comment by olli0815** [comment]
reading the changed numbers from cloud is not working.
I changed the minutes + 10 to 
![image](https://github.com/user-attachments/assets/b25cbeb3-89d6-4596-94b2-8a7259b7d9ba)

iob growatt.read brings nothing up, still old value after read

![image](https://github.com/user-attachments/assets/be03213d-ea49-40bc-b640-a7d719e50836)

**Comment by PLCHome** [comment]
This is the minute type of mix that works with 0
```
{
  "type": "state",
  "common": {
    "name": "Time slot 2 start MI",
    "type": "number",
    "role": "value",
    "min": 0,
    "max": 60,
    "step": 1,
    "read": true,
    "write": true
  },
  "native": {},
  "from": "system.adapter.growatt.0",
  "user": "system.user.admin",
  "ts": 1729782354262,
  "_id": "growatt.0.x.devices.x.settings.batteryFirst.values.param10",
  "acl": {
    "object": 1636,
    "state": 1636,
    "owner": "system.user.admin",
    "ownerGroup": "system.group.administrator"
  }
}
```

**Comment by olli0815** [comment]
{
  "type": "state",
  "common": {
    "name": "Start MI",
    "type": "number",
    "role": "value",
    "min": 0,
    "max": 60,
    "step": 1,
    "read": true,
    "write": true
  },
  "native": {},
  "from": "system.adapter.growatt.0",
  "user": "system.user.admin",
  "ts": 1729785788402,
  "_id": "growatt.0.1929535.devices.aaaaaaaaaaaaa.settings.timeSlot1.values.param3",
  "acl": {
    "object": 1636,
    "state": 1636,
    "owner": "system.user.admin",
    "ownerGroup": "system.group.administrator"
  }
}

**Comment by olli0815** [comment]
looks the same here

**Comment by olli0815** [comment]
okay that works even with 0,
so write works completely fine

**Comment by PLCHome** [comment]
Please add these three lines in the file “growatt.js” in the directory “growatt/lib” to debug the reading on line 37

```
const debug = require('debug');
debug.enable('growatt:api');
debug.enable('growatt:verbose');
```


![image](https://github.com/user-attachments/assets/c4c9afb8-b0f0-4f6e-9c5e-4123b6eb6ec5)

**Comment by PLCHome** [comment]
But I'm going to finish work now

**Comment by olli0815** [comment]
sure thanks !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
Don*t forget to send me the "buy my a coffee" link

**Comment by olli0815** [comment]
growatt.0
	2024-10-24 18:20:28.152	debug	Read inverter setting pvOnOff : {"msg":"1","success":true,"param1":1}
growatt.0
	2024-10-24 18:20:26.943	debug	Read inverter setting timeSlot9 : {"msg":"0-0-","success":false}
growatt.0
	2024-10-24 18:20:25.700	debug	Read inverter setting timeSlot8 : {"msg":"0-0-","success":false}
growatt.0
	2024-10-24 18:20:24.341	debug	Read inverter setting timeSlot7 : {"msg":"0-0-","success":false}
growatt.0
	2024-10-24 18:20:23.095	debug	Read inverter setting timeSlot6 : {"msg":"0-0-","success":false}
growatt.0
	2024-10-24 18:20:21.856	debug	Read inverter setting timeSlot5 : {"msg":"0-0-","success":false}
growatt.0
	2024-10-24 18:20:20.570	debug	Read inverter setting timeSlot4 : {"msg":"0-0-","success":false}
growatt.0
	2024-10-24 18:20:19.341	debug	Read inverter setting timeSlot3 : {"msg":"8192-1024-","success":false}
growatt.0
	2024-10-24 16:20:18.011	debug	Read inverter setting timeSlot2 : {"msg":"41728-1054-","success":false}
growatt.0
	2024-10-24 16:20:16.660	debug	Read inverter setting timeSlot1 : {"msg":"11776-4096-","success":false}
growatt.0
	2024-10-24 16:20:15.441	debug	Read inverter setting pvActivePRate : {"msg":"100","success":true,"param1":100}
growatt.0
	2024-10-24 16:20:14.021	debug	Read inverter setting time : {"msg":"2024-10-24-18-21-52-","success":true,"param1":1729794112000}
growatt.0
	2024-10-24 16:20:12.110	debug	Growatt time for settings : 20ms
growatt.0
	2024-10-24 16:20:12.110	debug	Leave growattData :2502ms
growatt.0
	2024-10-24 16:20:12.090	debug	Growatt time for parseData : 94ms
growatt.0
	2024-10-24 16:20:12.090	debug	Growatt time for settings : 94ms

**Comment by olli0815** [comment]
reading seems to work providing the values as DP not

**Comment by PLCHome** [comment]
Fuck...
change 
```
static parseTLXHTimeSlot(val, resolve) {
    debugApi('parseTLXHTimeSlot:', val);
    if (val.success === true && val.msg) {
      const ar = val.msg
        .toString()
        .split('-')
        .map(n => parseInt(n, 10));
      if (ar.length > 18) {
```

```
      if (ar.length > 2) {
```

Line 120 in https://github.com/PLCHome/growatt/blob/master/lib/parseret.js

**Comment by PLCHome** [comment]
> Don*t forget to send me the "buy my a coffee" link

I didn't have one, if you want you can use PLChome (at) fontanestr (dot) de  on paypal

**Comment by PLCHome** [comment]
> don't receive a message for the "time" data point as well

read:
on my inverter its:
action: readMixParam
paramId: pf_sys_time_mutli
serialNum: NxxxC
startAddr: -1
endAddr: -1

{"msg":"2024-10-25-10-8-38-","success":true}

Write:
action: mixSet
serialNum: NxxxxxC
type: pf_sys_year
param1: 2024-10-25 10:12

{"msg":"inv_set_success","success":true}

Maybe the date is transmitted differently here on the TLHX.

**Comment by PLCHome** [comment]
Then please change the length check from 18 to 1 this evening and it will work.

Then please check the problem with the zeros again. If that still doesn't work, I will add a workaround.

**Comment by olli0815** [comment]
something seems to be wrong with the data points.
My simple blockly to set a deified time slot ((3 in this case):
![image](https://github.com/user-attachments/assets/19ab45c4-4907-4224-b5aa-f3a743c1d812)
through a message that the "ack" false when I try to set the value via blockly.

growatt.0	11:58:23.328	silly	States user redis pmessage growatt.0.*.write/**growatt.0.1929535.devices.klklkklk.settings.timeSlot3.write:****{"val":true,"ack":false,"ts":1729850303318,"q":0,"c":"script.j**s.MeineSkripte.pv.Load_Battery","from":"system.adapter.javascript.0","user":"system.user.admin","lc":1729850303318}****

**Comment by olli0815** [comment]
so I can set the values via Admin GUI but not via script

**Comment by PLCHome** [comment]
It is not necessary to set "Write to Inverter" to false. Rewrite with value=true ack=false triggers it.
Just as it shown in the log.
Maybe that will solve the problem.
Unfortunately, I'm a programmer and not a painter. I don't know Blocky and can't do anything with it.

Is the problem with the 0 values ​​still there?

**Comment by olli0815** [comment]
okay ;-)
the reading seems to work, after deleting settings node once again.
The Initial read after restarting:
![Uploading image.png…]()

**Comment by PLCHome** [comment]
If I look closely, it says:
Write false to write after 1 second
Write Enabled after 1/2 second
Write true to write directly
The last point needs 2 seconds...

**Comment by olli0815** [comment]
net schlecht !!! Läuft.
my script initialized the value while setting  it 1 sec later - stupid mistake ;-(
Thanks !!!!

**Comment by PLCHome** [comment]
Ok, now that everything is running I'll build a test release.

Ok?

**Comment by olli0815** [comment]
yes, reading normal time is working as well

**Comment by PLCHome** [comment]
Does the THLX have a switch for charging from the grid? I used this function on my inverter at Tibber at reasonable prices.

**Comment by olli0815** [comment]
Yes, I thought it at well.
It's a simple parameter.
Will provide details tomorrow.

**Comment by olli0815** [comment]
write:
action	"tlxSet"
serialNum	"CZjllljl04A"
type	"ac_charge"
param1	"1"

response
"msg": "inv_set_success",
"success": true

read
action	"readMinParam"
paramId	"ac_charge"
serialNum	"CZM0CMK04A"
startAddr	"-1"
endAddr	"-1"

response
"msg": "1",
"success": true

**Comment by PLCHome** [comment]
Are there any other interesting parameters? Battery maximum, minimum or something else?

**Comment by olli0815** [comment]
not yet, just started to play around with the inverter, evcc, PV FC and tibber.
Main use case was to avoid discharging battery when car needs to be loaded fast by evcc (solved with setting battery first at the same time) and charge the battery when PV Forecast is low - usually at 3:00 at night (Battery first for one hour at night).
I guess with being able to completely switch the inverter off as well, I should have enough settings for controlling the inverter,

**Comment by PLCHome** [comment]
Please change in the Growatt node: 
https://github.com/PLCHome/growatt/blob/master/lib/growatttype.js

If the parameter only has a value Boolean or % it goes quickly, they are already implemented :-)

**Comment by olli0815** [comment]
works, thanks again !!

**Comment by PLCHome** [comment]
If you need more settings or parameters feel free to open a new ticket.
