### ISSUE TITLE
Support for GroHome (GroBoost) devicves

### ISSUE THREAD

**Issue by rlutsch18** [PLCHome/ioBroker.growatt#53]
Hello!

I have installed GroBoost device which is stearing a heating pipe for my hot water tank.
Additionally to the data of the inverter and the smartmeter, it would be great to have data for this device too.
Are there some plans?

BTW - the adapter works great - well done work!!

BR Richard

**Comment by PLCHome** [comment]
if you can debug the web interface with F12 in browser and provide information then yes, otherwise no, because I don't have that device.

**Comment by PLCHome** [comment]
If you can give me a URL that returns a JSON with parameters I can try to implement it, otherwise unfortunately not.

**Comment by rlutsch18** [comment]
Hello!

Thank you for your response!

The device is not directly accessible via the network - it is connected 
to a Shinelink-X RF device, which
is pushing the data via a GROTT Docker Proxy to the servers.growatt.com 
website. With this interception
of the webservice I am able to use the data locally for pushing it to 
PVOutput.org. I think the GROTT server also has not the availability to
decode the the shineboost device, because it's relativly new hardware. I 
am not getting exactly what you like to see with the developer tools - I 
have only the possibility
to see the Growatt's Statistics dashboard, but there is no REST API or 
something which I can use and therefore debug.
This stuff is absolutely not important for me, so you not have to put 
time on it - only you are interested in :-)

BTW - I am from Austria and we can talk german if possible for you :-)

This




------ Originalnachricht ------
Von "PLCHome" ***@***.***>
An "PLCHome/ioBroker.growatt" ***@***.***>
Cc "rlutsch18" ***@***.***>; "Author" 
***@***.***>
Datum 23.10.2024 14:05:49
Betreff Re: [PLCHome/ioBroker.growatt] Support for GroHome (GroBoost) 
devicves (Issue #53)

**Comment by PLCHome** [comment]
Everything this adapter reads from the web interface is JSON. If the JSON isn't there, I can't do anything.
